from __future__ import annotations

import os
import sys
from pathlib import Path

import pytest
from fastapi.testclient import TestClient
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool

os.environ["DB_INIT_MODE"] = "none"

BACKEND = Path(__file__).resolve().parents[1]
if str(BACKEND) not in sys.path:
    sys.path.insert(0, str(BACKEND))

from app.core.config import bootstrap_storage_tree, settings
from app.api.deps import get_db
from app.db.session import Base
from main import app

_H64 = "a" * 64

_SEAM_CODES = {
    "sec_xbrl_in_app_auth_policy_untrusted_proxy_identity",
    "sec_xbrl_in_app_auth_policy_missing_identity_authority",
    "sec_xbrl_in_app_auth_policy_missing_workspace_authority",
}

_IDENTITY_CANARY = "leak-canary-operator@example.invalid"
_GROUPS_CANARY = "leak-canary-groups@example.invalid"

_PREFIX = "/api/v1/layer3"


def _p(suffix: str) -> str:
    return _PREFIX + suffix


ALL_POST_ROUTES = [
    _p("/source/intake/upload"),
    _p("/source/ingestion/candidate-b/bundle/material-bridge"),
    _p("/source/ingestion/candidate-b/runtime/material-bridge"),
    _p("/source/ingestion/candidate-b/runtime/material-bridge/source-scan"),
    _p("/source/ingestion/candidate-b/artifact-family/status"),
    _p("/source/ingestion/candidate-b/visual-lane/status"),
    _p("/source/ingestion/candidate-b/runtime/downstream-proof"),
    _p("/source/ingestion/candidate-b/bundle/downstream-proof"),
    _p("/source/ingestion/candidate-b/default-promotion/operator-status"),
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/run"),
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/status"),
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/lifecycle/expire"),
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/queue/state"),
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/scheduler/lease"),
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/worker/attempt"),
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/progress/checkpoint"),
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/completion/failure"),
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/retry/policy"),
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/retry/queue/state"),
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/retry/scheduler/lease"),
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/retry/worker/attempt"),
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/retry/progress/checkpoint"),
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/retry/completion/failure"),
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/execution/boundary"),
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/process/execution"),
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/process/completion/result"),
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/process/completion/result/downstream-proof"),
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/completion/monitor"),
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/repeatability/checkpoint"),
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/repeatability/rerun-trial"),
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/repeatability/acceptance-checkpoint"),
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/repeatability/acceptance-closeout"),
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/repeatability/acceptance-closeout/status"),
    _p("/source/ingestion/candidate-b/default-promotion/closure-evidence"),
    _p("/source/ingestion/candidate-b/default-promotion/readiness-audit"),
    _p("/source/ingestion/candidate-b/broader-eligible-corpus/scope-readiness-audit"),
    _p("/source/ingestion/candidate-b/broader-eligible-corpus/default-scope/runtime"),
    _p("/source/ingestion/candidate-b/broader-eligible-corpus/default-scope/selector-use"),
    _p("/source/ingestion/candidate-b/broader-eligible-corpus/default-scope/selector-use/status"),
    _p("/source/ingestion/candidate-b/broader-eligible-corpus/default-scope/selector-activation"),
    _p("/source/ingestion/candidate-b/broader-eligible-corpus/default-scope/activation-receipt/consume"),
    _p("/source/ingestion/candidate-b/broader-eligible-corpus/default-scope/consumption-receipt/use"),
    _p("/source/ingestion/candidate-b/broader-eligible-corpus/default-scope/consumption-receipt/use/status"),
    _p("/source/ingestion/candidate-b/broader-eligible-corpus/default-scope/operator-repeatability/trial"),
    _p("/source/ingestion/candidate-b/broader-eligible-corpus/default-scope/promotion-readiness"),
    _p("/source/ingestion/candidate-b/broader-eligible-corpus/default-scope/default-promotion"),
    _p("/source/ingestion/candidate-b/default-promotion/final-proof"),
    _p("/source/ingestion/candidate-b/default-promotion/final-proof/status"),
    _p("/source/ingestion/server-configured-directory/scan"),
    _p("/source/ingestion/server-configured-directory/material-preview"),
    _p("/source/ingestion/server-configured-directory/hybrid-authority/prepare"),
    _p("/source/ingestion/server-configured-directory/vector-retrieval"),
    _p("/source/ingestion/server-configured-directory/hybrid-context-packet"),
    _p("/source/ingestion/server-configured-directory/hybrid-context-packet/qualitative-analysis"),
    _p("/source/ingestion/server-configured-directory/hybrid-context-packet/qualitative-analysis/status"),
    _p("/source/ingestion/server-configured-directory/hybrid-context-packet/qualitative-analysis/package/commit"),
    _p("/source/ingestion/server-configured-directory/hybrid-context-packet/qualitative-analysis/package/review/submit"),
    _p("/source/ingestion/server-configured-directory/hybrid-context-packet/qualitative-analysis/handoff/export/prepare"),
    _p("/source/ingestion/server-configured-directory/hybrid-context-packet/qualitative-analysis/handoff/export/download/prepare"),
    _p("/source/ingestion/server-configured-directory/hybrid-context-packet/qualitative-analysis/handoff/export/internal-webhook/dispatch"),
    _p("/source/ingestion/server-configured-directory/hybrid-context-packet/qualitative-analysis/handoff/export/download/deliver/status"),
    _p("/source/ingestion/server-configured-directory/hybrid-context-packet/qualitative-analysis/handoff/export/download/provider-private-signed-url/prepare"),
    _p("/source/ingestion/server-configured-directory/hybrid-context-packet/qualitative-analysis/handoff/export/download/provider-private-signed-url/status"),
    _p("/source/ingestion/server-configured-directory/hybrid-context-packet/qualitative-analysis/handoff/export/download/provider-private-signed-url/use"),
    _p("/source/ingestion/server-configured-directory/hybrid-context-packet/qualitative-analysis/handoff/export/download/provider-private-signed-url/revoke"),
    _p("/source/ingestion/server-configured-directory/hybrid-context-packet/qualitative-analysis/handoff/export/download/deliver"),
    _p("/source/ingestion/server-configured-directory/qualitative-hybrid-analysis"),
    _p("/source/ingestion/server-configured-directory/qualitative-hybrid-analysis/status"),
    _p("/source/ingestion/server-configured-directory/qualitative-hybrid-analysis/package/commit"),
    _p("/source/ingestion/server-configured-directory/qualitative-hybrid-analysis/package/review/submit"),
    _p("/source/ingestion/server-configured-directory/qualitative-hybrid-analysis/package/supersession/preview"),
    _p("/source/ingestion/server-configured-directory/qualitative-hybrid-analysis/package/replacement-set/record-from-supersession-preview"),
    _p("/source/ingestion/server-configured-directory/qualitative-hybrid-analysis/package/supersession/commit"),
    _p("/source/ingestion/server-configured-directory/qualitative-hybrid-analysis/package/supersession/provider-private-signed-url/prepare"),
    _p("/source/ingestion/server-configured-directory/qualitative-hybrid-analysis/package/supersession/provider-private-signed-url/status"),
    _p("/source/ingestion/server-configured-directory/qualitative-hybrid-analysis/package/supersession/provider-private-signed-url/use"),
    _p("/source/ingestion/server-configured-directory/qualitative-hybrid-analysis/package/supersession/provider-private-signed-url/revoke"),
    _p("/source/ingestion/server-configured-directory/qualitative-hybrid-analysis/handoff/export/prepare"),
    _p("/source/ingestion/server-configured-directory/qualitative-hybrid-analysis/handoff/export/download/prepare"),
    _p("/source/ingestion/server-configured-directory/qualitative-hybrid-analysis/handoff/export/download/deliver/status"),
    _p("/source/ingestion/server-configured-directory/qualitative-hybrid-analysis/handoff/export/download/deliver"),
    _p("/source/mixed-corpus/seed"),
    _p("/source/mixed-corpus/materialize"),
]

_FILE_RESPONSE_ROUTES = {
    _p("/source/ingestion/server-configured-directory/hybrid-context-packet/qualitative-analysis/handoff/export/download/deliver"),
    _p("/source/ingestion/server-configured-directory/qualitative-hybrid-analysis/handoff/export/download/deliver"),
}

_HASH_FIELDS = (
    "content_sha256",
    "file_identity_hash",
    "authority_basis_hash",
    "payload_hash",
    "index_authority_hash",
    "embedding_index_authority_hash",
    "qualitative_analysis_hash",
    "source_directory_package_review_preview_hash",
    "construction_basis_hash",
    "package_payload_hash",
    "package_supersession_preview_hash",
    "source_directory_hybrid_package_review_preview_hash",
)

_ROUTE_PAYLOADS: dict[str, dict] = {
    _p("/source/intake/upload"): None,
    _p("/source/ingestion/candidate-b/bundle/material-bridge"): {
        "client_request_id": "x",
        "bridge_mode": "candidate_b_bundle_curated_json_md_to_layer3_material_authority_v1",
        "candidate_b_bundle_id": "b",
        "baseline_run_id": "bl",
        "candidate_a_run_id": "ca",
        "operator_confirmation": True,
    },
    _p("/source/ingestion/candidate-b/runtime/material-bridge"): {
        "client_request_id": "x",
        "bridge_mode": "candidate_b_runtime_source_to_layer3_material_authority_v1",
        "candidate_b_run_id": "r",
        "baseline_run_id": "bl",
        "candidate_a_run_id": "ca",
        "operator_confirmation": True,
    },
    _p("/source/ingestion/candidate-b/runtime/material-bridge/source-scan"): {
        "client_request_id": "x",
        "source_scan_mode": "candidate_b_runtime_bridge_curated_source_scan_v1",
        "operator_decision": "scan_candidate_b_runtime_bridge_curated_material_root",
        "bridge_receipt_id": "br",
        "candidate_b_run_id": "r",
        "baseline_run_id": "bl",
        "candidate_a_run_id": "ca",
        "operator_confirmation": True,
    },
    _p("/source/ingestion/candidate-b/artifact-family/status"): {
        "client_request_id": "x",
        "status_mode": "candidate_b_retained_artifact_family_status_v1",
        "operator_decision": "inspect_candidate_b_governed_retained_artifact_family_status",
        "candidate_b_source_kind": "bundle",
        "bridge_receipt_id": "br",
    },
    _p("/source/ingestion/candidate-b/visual-lane/status"): {
        "client_request_id": "x",
        "status_mode": "candidate_b_visual_lane_status_v1",
        "operator_decision": "inspect_candidate_b_visual_lane_evidence_status",
        "candidate_b_run_id": "r",
        "bridge_receipt_id": "br",
    },
    _p("/source/ingestion/candidate-b/runtime/downstream-proof"): {
        "client_request_id": "x",
        "proof_mode": "candidate_b_visual_lane_runtime_downstream_e2e_proof_v1",
        "operator_decision": "record_candidate_b_visual_lane_runtime_downstream_e2e_proof",
        "candidate_b_run_id": "r",
        "bridge_receipt_id": "br",
        "candidate_b_visual_lane_status_evidence": {},
        "coverage_evidence": {},
        "operator_confirmation": True,
    },
    _p("/source/ingestion/candidate-b/bundle/downstream-proof"): {
        "client_request_id": "x",
        "proof_mode": "candidate_b_bundle_downstream_e2e_proof_v1",
        "operator_decision": "record_candidate_b_bundle_downstream_e2e_proof",
        "candidate_b_bundle_id": "b",
        "bridge_receipt_id": "br",
        "coverage_evidence": {},
        "operator_confirmation": True,
    },
    _p("/source/ingestion/candidate-b/default-promotion/operator-status"): {
        "client_request_id": "x",
        "status_mode": "candidate_b_default_promotion_operator_status_v1",
        "operator_decision": "inspect_candidate_b_default_promotion_operator_status",
        "baseline_run_id": "bl",
        "candidate_a_run_id": "ca",
        "candidate_b_bundle_id": "b",
        "candidate_b_run_id": "r",
        "candidate_b_bundle_bridge_receipt_id": "bbr",
        "candidate_b_runtime_bridge_receipt_id": "rbr",
        "candidate_b_visual_lane_status_evidence": {},
        "runtime_downstream_proof": {},
    },
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/run"): {
        "client_request_id": "x",
        "run_mode": "candidate_b_full_corpus_operator_workflow_run_v1",
        "operator_decision": "start_candidate_b_full_corpus_operator_workflow",
        "runtime_root_lifecycle_receipt_id": "r",
        "baseline_run_id": "bl",
        "candidate_a_run_id": "ca",
        "candidate_b_run_id": "cr",
        "compare_target_set_hash": _H64,
    },
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/status"): {
        "client_request_id": "x",
        "status_mode": "candidate_b_full_corpus_operator_workflow_status_v1",
        "operator_decision": "inspect_candidate_b_full_corpus_operator_workflow_status",
        "operator_workflow_receipt_id": "wr",
        "baseline_run_id": "bl",
        "candidate_a_run_id": "ca",
        "candidate_b_run_id": "cr",
        "bridge_receipt_id": "br",
        "downstream_proof_id": "dp",
    },
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/lifecycle/expire"): {
        "client_request_id": "x",
        "lifecycle_mode": "candidate_b_operator_workflow_run_expiry_closeout_receipt_v1",
        "operator_decision": "expire_or_close_server_owned_workflow_run_receipt",
        "operator_workflow_receipt_id": "wr",
        "operator_workflow_receipt_hash": _H64,
        "row_hash": _H64,
        "authority_basis_hash": _H64,
        "history_hash": _H64,
    },
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/queue/state"): {
        "client_request_id": "x",
        "queue_state_mode": "append_only_queue_state_receipt_without_background_scheduler",
        "operator_decision": "record_candidate_b_async_workflow_queue_state",
        "operator_workflow_receipt_id": "wr",
        "operator_workflow_receipt_hash": _H64,
        "row_hash": _H64,
        "authority_basis_hash": _H64,
        "history_hash": _H64,
    },
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/scheduler/lease"): {
        "client_request_id": "x",
        "scheduler_lease_mode": "append_only_scheduler_lease_receipt_without_background_worker",
        "operator_decision": "record_candidate_b_async_scheduler_lease",
        "queue_state_receipt_id": "qs",
        "queue_state_receipt_hash": _H64,
        "queue_state_authority_hash": _H64,
        "operator_workflow_receipt_id": "wr",
        "operator_workflow_receipt_hash": _H64,
        "row_hash": _H64,
        "authority_basis_hash": _H64,
        "history_hash": _H64,
    },
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/worker/attempt"): {
        "client_request_id": "x",
        "worker_attempt_mode": "append_only_worker_attempt_receipt_without_job_execution",
        "operator_decision": "record_candidate_b_async_worker_attempt",
        "worker_attempt_number": 1,
        "scheduler_lease_receipt_id": "sl",
        "scheduler_lease_receipt_hash": _H64,
        "scheduler_lease_authority_hash": _H64,
        "queue_state_receipt_id": "qs",
        "queue_state_receipt_hash": _H64,
        "queue_state_authority_hash": _H64,
        "operator_workflow_receipt_id": "wr",
        "operator_workflow_receipt_hash": _H64,
        "row_hash": _H64,
        "authority_basis_hash": _H64,
        "history_hash": _H64,
    },
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/progress/checkpoint"): {
        "client_request_id": "x",
        "progress_checkpoint_mode": "append_only_progress_checkpoint_receipt_without_completion_or_cancel_retry_resume",
        "operator_decision": "record_candidate_b_async_progress_checkpoint",
        "progress_checkpoint_sequence": 1,
        "worker_attempt_receipt_id": "wa",
        "worker_attempt_receipt_hash": _H64,
        "worker_attempt_authority_hash": _H64,
        "scheduler_lease_receipt_id": "sl",
        "scheduler_lease_receipt_hash": _H64,
        "scheduler_lease_authority_hash": _H64,
        "queue_state_receipt_id": "qs",
        "queue_state_receipt_hash": _H64,
        "queue_state_authority_hash": _H64,
        "operator_workflow_receipt_id": "wr",
        "operator_workflow_receipt_hash": _H64,
        "row_hash": _H64,
        "authority_basis_hash": _H64,
        "history_hash": _H64,
    },
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/completion/failure"): {
        "client_request_id": "x",
        "completion_failure_mode": "append_only_completion_failure_receipt_without_cancel_retry_resume_or_source_receipt_mutation",
        "operator_decision": "record_candidate_b_async_completion_failure",
        "terminal_outcome": "completed",
        "latest_progress_checkpoint_receipt_id": "lp",
        "latest_progress_checkpoint_receipt_hash": _H64,
        "latest_progress_checkpoint_authority_hash": _H64,
        "progress_checkpoint_sequence": 1,
        "worker_attempt_receipt_id": "wa",
        "worker_attempt_receipt_hash": _H64,
        "worker_attempt_authority_hash": _H64,
        "scheduler_lease_receipt_id": "sl",
        "scheduler_lease_receipt_hash": _H64,
        "scheduler_lease_authority_hash": _H64,
        "queue_state_receipt_id": "qs",
        "queue_state_receipt_hash": _H64,
        "queue_state_authority_hash": _H64,
        "operator_workflow_receipt_id": "wr",
        "operator_workflow_receipt_hash": _H64,
        "row_hash": _H64,
        "authority_basis_hash": _H64,
        "history_hash": _H64,
    },
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/retry/policy"): {
        "client_request_id": "x",
        "retry_policy_mode": "append_only_retry_policy_receipt_without_creating_retry_attempt_or_mutating_terminal_receipts",
        "operator_decision": "record_candidate_b_async_retry_policy",
        "retry_policy_result": "eligible",
        "retry_policy_reason": "r",
        "completion_failure_receipt_id": "cf",
        "completion_failure_receipt_hash": _H64,
        "completion_failure_authority_hash": _H64,
        "terminal_outcome": "failed",
        "terminal_outcome_hash": _H64,
        "latest_progress_checkpoint_receipt_id": "lp",
        "latest_progress_checkpoint_receipt_hash": _H64,
        "latest_progress_checkpoint_authority_hash": _H64,
        "progress_checkpoint_sequence": 1,
        "worker_attempt_receipt_id": "wa",
        "worker_attempt_receipt_hash": _H64,
        "worker_attempt_authority_hash": _H64,
        "scheduler_lease_receipt_id": "sl",
        "scheduler_lease_receipt_hash": _H64,
        "scheduler_lease_authority_hash": _H64,
        "queue_state_receipt_id": "qs",
        "queue_state_receipt_hash": _H64,
        "queue_state_authority_hash": _H64,
        "operator_workflow_receipt_id": "wr",
        "operator_workflow_receipt_hash": _H64,
        "row_hash": _H64,
        "authority_basis_hash": _H64,
        "history_hash": _H64,
    },
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/retry/queue/state"): {
        "client_request_id": "x",
        "retry_queue_state_mode": "append_only_retry_queue_state_receipt_without_creating_scheduler_lease_worker_attempt_or_mutating_original_lineage",
        "operator_decision": "record_candidate_b_async_retry_queue_state",
        "retry_policy_receipt_id": "rp",
        "retry_policy_receipt_hash": _H64,
        "retry_policy_authority_hash": _H64,
        "retry_policy_result": "eligible",
        "completion_failure_receipt_id": "cf",
        "completion_failure_receipt_hash": _H64,
        "completion_failure_authority_hash": _H64,
        "failed_worker_attempt_receipt_id": "fw",
        "failed_worker_attempt_authority_hash": _H64,
        "operator_workflow_receipt_id": "wr",
        "operator_workflow_receipt_hash": _H64,
        "row_hash": _H64,
        "authority_basis_hash": _H64,
        "history_hash": _H64,
    },
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/retry/scheduler/lease"): {
        "client_request_id": "x",
        "retry_scheduler_lease_mode": "append_only_retry_scheduler_lease_receipt_without_creating_worker_attempt_or_mutating_retry_queue_state_original_lineage",
        "operator_decision": "record_candidate_b_async_retry_scheduler_lease",
        "retry_queue_state_receipt_id": "rqs",
        "retry_queue_state_receipt_hash": _H64,
        "retry_queue_state_authority_hash": _H64,
        "retry_attempt_number": 2,
        "retry_policy_receipt_id": "rp",
        "retry_policy_authority_hash": _H64,
        "completion_failure_receipt_id": "cf",
        "failed_worker_attempt_receipt_id": "fw",
        "operator_workflow_receipt_id": "wr",
        "operator_workflow_receipt_hash": _H64,
        "row_hash": _H64,
        "authority_basis_hash": _H64,
        "history_hash": _H64,
    },
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/retry/worker/attempt"): {
        "client_request_id": "x",
        "retry_worker_attempt_mode": "append_only_retry_worker_attempt_receipt_without_job_execution",
        "operator_decision": "record_candidate_b_async_retry_worker_attempt",
        "retry_attempt_number": 2,
        "retry_scheduler_lease_receipt_id": "rsl",
        "retry_scheduler_lease_receipt_hash": _H64,
        "retry_scheduler_lease_authority_hash": _H64,
        "retry_queue_state_receipt_id": "rqs",
        "retry_queue_state_receipt_hash": _H64,
        "retry_queue_state_authority_hash": _H64,
        "retry_policy_receipt_id": "rp",
        "retry_policy_authority_hash": _H64,
        "completion_failure_receipt_id": "cf",
        "failed_worker_attempt_receipt_id": "fw",
        "operator_workflow_receipt_id": "wr",
        "operator_workflow_receipt_hash": _H64,
        "row_hash": _H64,
        "authority_basis_hash": _H64,
        "history_hash": _H64,
    },
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/retry/progress/checkpoint"): {
        "client_request_id": "x",
        "retry_progress_checkpoint_mode": "append_only_retry_progress_checkpoint_receipt_without_retry_completion_cancel_resume_or_job_execution",
        "operator_decision": "record_candidate_b_async_retry_progress_checkpoint",
        "retry_progress_checkpoint_sequence": 1,
        "retry_attempt_number": 2,
        "retry_worker_attempt_receipt_id": "rwa",
        "retry_worker_attempt_receipt_hash": _H64,
        "retry_worker_attempt_authority_hash": _H64,
        "retry_scheduler_lease_receipt_id": "rsl",
        "retry_scheduler_lease_receipt_hash": _H64,
        "retry_scheduler_lease_authority_hash": _H64,
        "retry_queue_state_receipt_id": "rqs",
        "retry_queue_state_receipt_hash": _H64,
        "retry_queue_state_authority_hash": _H64,
        "retry_policy_receipt_id": "rp",
        "retry_policy_authority_hash": _H64,
        "completion_failure_receipt_id": "cf",
        "failed_worker_attempt_receipt_id": "fw",
        "operator_workflow_receipt_id": "wr",
        "operator_workflow_receipt_hash": _H64,
        "row_hash": _H64,
        "authority_basis_hash": _H64,
        "history_hash": _H64,
    },
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/retry/completion/failure"): {
        "client_request_id": "x",
        "retry_completion_failure_mode": "append_only_retry_completion_failure_receipt_without_cancel_resume_job_execution_or_source_receipt_mutation",
        "operator_decision": "record_candidate_b_async_retry_completion_failure",
        "retry_terminal_outcome": "completed",
        "retry_attempt_number": 2,
        "latest_retry_progress_checkpoint_receipt_id": "lrp",
        "latest_retry_progress_checkpoint_receipt_hash": _H64,
        "latest_retry_progress_checkpoint_authority_hash": _H64,
        "retry_progress_checkpoint_sequence": 1,
        "retry_worker_attempt_receipt_id": "rwa",
        "retry_worker_attempt_receipt_hash": _H64,
        "retry_worker_attempt_authority_hash": _H64,
        "retry_scheduler_lease_receipt_id": "rsl",
        "retry_scheduler_lease_receipt_hash": _H64,
        "retry_scheduler_lease_authority_hash": _H64,
        "retry_queue_state_receipt_id": "rqs",
        "retry_queue_state_receipt_hash": _H64,
        "retry_queue_state_authority_hash": _H64,
        "retry_policy_receipt_id": "rp",
        "retry_policy_receipt_hash": _H64,
        "retry_policy_authority_hash": _H64,
        "completion_failure_receipt_id": "cf",
        "completion_failure_receipt_hash": _H64,
        "completion_failure_authority_hash": _H64,
        "failed_worker_attempt_receipt_id": "fw",
        "failed_worker_attempt_receipt_hash": _H64,
        "failed_worker_attempt_authority_hash": _H64,
        "operator_workflow_receipt_id": "wr",
        "operator_workflow_receipt_hash": _H64,
        "row_hash": _H64,
        "authority_basis_hash": _H64,
        "history_hash": _H64,
    },
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/execution/boundary"): {
        "client_request_id": "x",
        "execution_boundary_mode": "append_only_execution_boundary_receipt_without_process_start_or_job_execution",
        "operator_decision": "record_candidate_b_async_background_job_execution_boundary",
        "operator_workflow_receipt_id": "wr",
        "operator_workflow_receipt_hash": _H64,
        "row_hash": _H64,
        "authority_basis_hash": _H64,
        "history_hash": _H64,
    },
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/process/execution"): {
        "client_request_id": "x",
        "process_execution_mode": "server_owned_allowlisted_process_start_with_redacted_receipt_and_no_browser_command_authority",
        "operator_decision": "record_candidate_b_async_background_process_execution",
        "operator_workflow_receipt_id": "wr",
        "operator_workflow_receipt_hash": _H64,
        "row_hash": _H64,
        "authority_basis_hash": _H64,
        "history_hash": _H64,
        "execution_boundary_receipt_id": "eb",
        "execution_boundary_receipt_hash": _H64,
        "execution_boundary_authority_hash": _H64,
    },
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/process/completion/result"): {
        "client_request_id": "x",
        "process_completion_result_mode": "append_only_process_completion_result_adoption_receipt_without_source_run_mutation_or_raw_output_exposure",
        "operator_decision": "record_candidate_b_async_process_completion_result_adoption",
        "terminal_state": "completed",
        "operator_workflow_receipt_id": "wr",
        "operator_workflow_receipt_hash": _H64,
        "row_hash": _H64,
        "authority_basis_hash": _H64,
        "history_hash": _H64,
        "process_execution_receipt_id": "pe",
        "process_execution_receipt_hash": _H64,
        "process_execution_authority_hash": _H64,
    },
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/process/completion/result/downstream-proof"): {
        "client_request_id": "x",
        "adopted_result_downstream_proof_mode": "read_only_adopted_process_result_downstream_operator_proof_without_result_mutation_or_reexecution",
        "operator_decision": "record_candidate_b_async_adopted_process_result_downstream_operator_proof",
        "operator_workflow_receipt_id": "wr",
        "operator_workflow_receipt_hash": _H64,
        "row_hash": _H64,
        "authority_basis_hash": _H64,
        "history_hash": _H64,
        "process_completion_result_receipt_id": "pcr",
        "process_completion_result_receipt_hash": _H64,
        "process_completion_result_authority_hash": _H64,
        "process_execution_receipt_id": "pe",
        "process_execution_receipt_hash": _H64,
        "process_execution_authority_hash": _H64,
        "result_workflow_receipt_id": "rw",
        "result_workflow_receipt_hash": _H64,
        "result_status_request_hash": _H64,
        "result_downstream_proof_hash": _H64,
    },
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/completion/monitor"): {
        "client_request_id": "x",
        "completion_monitor_mode": "read_only_operator_workflow_completion_monitor_without_process_control_result_mutation_or_reexecution",
        "operator_decision": "inspect_candidate_b_async_operator_workflow_completion_monitor",
        "operator_workflow_receipt_id": "wr",
        "operator_workflow_receipt_hash": _H64,
        "row_hash": _H64,
        "authority_basis_hash": _H64,
        "history_hash": _H64,
    },
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/repeatability/checkpoint"): {
        "client_request_id": "x",
        "repeatability_checkpoint_mode": "append_only_repeatability_checkpoint_receipt_without_rerun_process_control_or_authority_mutation",
        "operator_decision": "record_candidate_b_full_corpus_operator_repeatability_checkpoint",
        "operator_workflow_receipt_id": "wr",
        "operator_workflow_receipt_hash": _H64,
        "row_hash": _H64,
        "authority_basis_hash": _H64,
        "history_hash": _H64,
        "workflow_status_hash": _H64,
        "completion_monitor_hash": _H64,
        "runtime_root_lifecycle_receipt_id": "rl",
        "bridge_receipt_id": "br",
        "downstream_proof_id": "dp",
        "baseline_run_id": "bl",
        "candidate_a_run_id": "ca",
        "candidate_b_run_id": "cr",
        "compare_target_set_hash": _H64,
        "material_relative_name": "m",
        "operator_runbook_repeatability_steps": ["s1", "s2", "s3", "s4"],
    },
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/repeatability/rerun-trial"): {
        "client_request_id": "x",
        "rerun_trial_mode": "append_only_repeatability_rerun_trial_receipt_without_process_execution_or_authority_mutation",
        "operator_decision": "record_candidate_b_full_corpus_repeatability_rerun_trial",
        "original_repeatability_checkpoint_receipt_id": "orc",
        "original_repeatability_checkpoint_receipt_hash": _H64,
        "original_repeatability_checkpoint_hash": _H64,
        "original_repeatability_checkpoint_authority_hash": _H64,
        "original_operator_workflow_receipt_id": "owr",
        "original_operator_workflow_receipt_hash": _H64,
        "original_row_hash": _H64,
        "original_authority_basis_hash": _H64,
        "original_history_hash": _H64,
        "original_workflow_status_hash": _H64,
        "original_completion_monitor_hash": _H64,
        "rerun_operator_workflow_receipt_id": "rwr",
        "rerun_operator_workflow_receipt_hash": _H64,
        "rerun_row_hash": _H64,
        "rerun_authority_basis_hash": _H64,
        "rerun_history_hash": _H64,
        "rerun_workflow_status_hash": _H64,
        "rerun_completion_monitor_hash": _H64,
        "baseline_run_id": "bl",
        "candidate_a_run_id": "ca",
        "original_candidate_b_run_id": "ocr",
        "rerun_candidate_b_run_id": "rcr",
        "compare_target_set_hash": _H64,
        "material_relative_name": "m",
        "regression_disposition": "no_regression_observed",
        "operator_runbook_repeatability_steps": ["s1", "s2", "s3", "s4", "s5", "s6", "s7"],
    },
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/repeatability/acceptance-checkpoint"): {
        "client_request_id": "x",
        "acceptance_checkpoint_mode": "append_only_acceptance_checkpoint_receipt_without_process_execution_or_authority_mutation",
        "operator_decision": "record_candidate_b_full_corpus_repeatability_acceptance_checkpoint",
        "operator_acceptance_decision": "accepted",
        "original_repeatability_checkpoint_receipt_id": "orc",
        "original_repeatability_checkpoint_receipt_hash": _H64,
        "original_repeatability_checkpoint_hash": _H64,
        "original_repeatability_checkpoint_authority_hash": _H64,
        "repeatability_rerun_trial_receipt_id": "rrt",
        "repeatability_rerun_trial_receipt_hash": _H64,
        "repeatability_rerun_trial_hash": _H64,
        "repeatability_rerun_trial_authority_hash": _H64,
        "original_workflow_status_hash": _H64,
        "original_completion_monitor_hash": _H64,
        "rerun_workflow_status_hash": _H64,
        "rerun_completion_monitor_hash": _H64,
        "acceptance_disposition": "no_regression_observed",
        "operator_runbook_repeatability_steps": ["s1", "s2", "s3", "s4"],
    },
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/repeatability/acceptance-closeout"): {
        "client_request_id": "x",
        "acceptance_closeout_mode": "append_only_acceptance_operator_closeout_receipt_without_process_execution_or_authority_mutation",
        "operator_decision": "record_candidate_b_full_corpus_repeatability_acceptance_operator_closeout",
        "repeatability_acceptance_checkpoint_receipt_id": "rac",
        "repeatability_acceptance_checkpoint_receipt_hash": _H64,
        "repeatability_acceptance_checkpoint_hash": _H64,
        "repeatability_acceptance_checkpoint_authority_hash": _H64,
        "acceptance_disposition": "no_regression_observed",
        "rendered_acceptance_control_mode": "rendered_candidate_b_full_corpus_repeatability_acceptance_closeout_control",
        "rendered_acceptance_control_proof_state": "headed_and_headless_passed",
        "headless_rendered_proof_label": "candidate_b_repeatability_acceptance_rendered_control_headless_chromium_pass",
        "headed_rendered_proof_label": "candidate_b_repeatability_acceptance_rendered_control_headed_chromium_pass",
        "operator_runbook_closeout_steps": ["s1", "s2", "s3", "s4"],
        "negative_invariant_attestations": {},
    },
    _p("/source/ingestion/candidate-b/full-corpus/operator-workflow/repeatability/acceptance-closeout/status"): {
        "client_request_id": "x",
        "closeout_status_mode": "read_only_acceptance_closeout_status_without_receipt_creation_lineage_mutation_or_frontend_authority",
        "operator_decision": "inspect_candidate_b_full_corpus_repeatability_acceptance_closeout_status",
    },
    _p("/source/ingestion/candidate-b/default-promotion/closure-evidence"): {
        "client_request_id": "x",
        "closure_mode": "candidate_b_default_promotion_closure_evidence_v1",
        "operator_decision": "record_candidate_b_default_promotion_closure_evidence",
        "baseline_run_id": "bl",
        "candidate_a_run_id": "ca",
        "candidate_b_bundle_id": "b",
        "candidate_b_run_id": "r",
        "candidate_b_bundle_bridge_receipt_id": "bbr",
        "candidate_b_runtime_bridge_receipt_id": "rbr",
        "eligible_corpus_scope": "s",
        "regression_disposition": "none",
        "rollback_to_baseline_confirmation": False,
        "operator_confirmation": True,
        "bundle_downstream_proof": {},
        "runtime_downstream_proof": {},
        "operator_status_evidence": {},
    },
    _p("/source/ingestion/candidate-b/default-promotion/readiness-audit"): {
        "client_request_id": "x",
        "readiness_mode": "candidate_b_default_promotion_readiness_audit_v1",
        "baseline_run_id": "bl",
        "candidate_a_run_id": "ca",
        "candidate_b_bundle_id": "b",
        "candidate_b_run_id": "r",
        "candidate_b_bundle_bridge_receipt_id": "bbr",
        "candidate_b_runtime_bridge_receipt_id": "rbr",
        "eligible_corpus_scope": "s",
        "regression_disposition": "none",
        "rollback_to_baseline_confirmation": False,
        "operator_confirmation": True,
        "bundle_downstream_proof": {},
        "runtime_downstream_proof": {},
        "candidate_b_visual_lane_status_evidence": {},
        "operator_status_evidence": {},
        "closure_evidence": {},
    },
    _p("/source/ingestion/candidate-b/broader-eligible-corpus/scope-readiness-audit"): {
        "client_request_id": "x",
        "audit_mode": "candidate_b_broader_eligible_corpus_scope_readiness_audit_v1",
        "exact_corpus_class_list": [],
        "explicit_exclusion_list": [],
        "proposed_default_scope_classes": [],
        "scope_evidence": {},
        "rollback_to_baseline_confirmation": False,
        "operator_confirmation": True,
    },
    _p("/source/ingestion/candidate-b/broader-eligible-corpus/default-scope/runtime"): {
        "client_request_id": "x",
        "runtime_mode": "candidate_b_broader_eligible_corpus_default_scope_runtime_v1",
        "readiness_audit_id": "ra",
        "readiness_audit_hash": "h",
        "selected_scope_classes": [],
        "rollback_to_baseline_confirmation": False,
        "operator_confirmation": True,
    },
    _p("/source/ingestion/candidate-b/broader-eligible-corpus/default-scope/selector-use"): {
        "client_request_id": "x",
        "selector_use_mode": "candidate_b_broader_eligible_corpus_default_scope_selector_use_runtime_v1",
        "runtime_selection_receipt_id": "rs",
        "runtime_selection_receipt_hash": "h",
        "selected_scope_classes": [],
        "rollback_to_baseline_confirmation": False,
        "operator_confirmation": True,
    },
    _p("/source/ingestion/candidate-b/broader-eligible-corpus/default-scope/selector-use/status"): {
        "client_request_id": "x",
        "status_mode": "candidate_b_broader_eligible_corpus_default_scope_selector_use_status_v1",
        "operator_decision": "inspect_candidate_b_broader_eligible_corpus_default_scope_selector_use_status",
        "selector_use_receipt_id": "su",
        "selector_use_receipt_hash": "h",
        "runtime_selection_receipt_id": "rs",
        "runtime_selection_receipt_hash": "h",
    },
    _p("/source/ingestion/candidate-b/broader-eligible-corpus/default-scope/selector-activation"): {
        "client_request_id": "x",
        "activation_mode": "candidate_b_broader_eligible_corpus_default_scope_selector_activation_runtime_v1",
        "selector_use_status_hash": "h",
        "selector_use_receipt_id": "su",
        "selector_use_receipt_hash": "h",
        "runtime_selection_receipt_id": "rs",
        "runtime_selection_receipt_hash": "h",
        "selected_scope_classes": [],
        "rollback_to_baseline_confirmation": False,
        "operator_confirmation": True,
    },
    _p("/source/ingestion/candidate-b/broader-eligible-corpus/default-scope/activation-receipt/consume"): {
        "client_request_id": "x",
        "consumption_mode": "candidate_b_broader_eligible_corpus_default_scope_activation_receipt_consumption_runtime_v1",
        "activation_receipt_id": "ar",
        "activation_receipt_hash": "h",
        "selector_use_status_hash": "h",
        "selector_use_receipt_id": "su",
        "selector_use_receipt_hash": "h",
        "runtime_selection_receipt_id": "rs",
        "runtime_selection_receipt_hash": "h",
        "selected_scope_classes": [],
        "rollback_to_baseline_confirmation": False,
        "operator_confirmation": True,
    },
    _p("/source/ingestion/candidate-b/broader-eligible-corpus/default-scope/consumption-receipt/use"): {
        "client_request_id": "x",
        "use_mode": "candidate_b_broader_eligible_corpus_default_scope_consumption_receipt_use_runtime_v1",
        "consumption_receipt_id": "cr",
        "consumption_receipt_hash": "h",
        "activation_receipt_id": "ar",
        "activation_receipt_hash": "h",
        "selector_use_status_hash": "h",
        "selector_use_receipt_id": "su",
        "selector_use_receipt_hash": "h",
        "runtime_selection_receipt_id": "rs",
        "runtime_selection_receipt_hash": "h",
        "selected_scope_classes": [],
        "rollback_to_baseline_confirmation": False,
        "operator_confirmation": True,
    },
    _p("/source/ingestion/candidate-b/broader-eligible-corpus/default-scope/consumption-receipt/use/status"): {
        "client_request_id": "x",
        "status_mode": "candidate_b_broader_eligible_corpus_default_scope_consumption_receipt_use_status_v1",
        "operator_decision": "inspect_candidate_b_broader_eligible_corpus_default_scope_consumption_receipt_use_status",
        "use_receipt_id": "ur",
        "use_receipt_hash": "h",
        "consumption_receipt_id": "cr",
        "consumption_receipt_hash": "h",
        "activation_receipt_id": "ar",
        "activation_receipt_hash": "h",
        "selector_use_status_hash": "h",
        "selector_use_receipt_id": "su",
        "selector_use_receipt_hash": "h",
        "runtime_selection_receipt_id": "rs",
        "runtime_selection_receipt_hash": "h",
        "readiness_audit_id": "ra",
        "readiness_audit_hash": "h",
        "selected_scope_classes": [],
    },
    _p("/source/ingestion/candidate-b/broader-eligible-corpus/default-scope/operator-repeatability/trial"): {
        "client_request_id": "x",
        "trial_mode": "append_only_trial_receipt_over_original_and_repeat_use_status_authority_without_processing_execution",
        "operator_decision": "record_candidate_b_broader_scope_operator_repeatability_trial",
        "operator_repeatability_disposition": "no_regression_observed",
        "selected_scope_classes": [],
        "original_use_receipt_status_hash": "h",
        "original_use_receipt_id": "our",
        "original_use_receipt_hash": "h",
        "original_consumption_receipt_id": "ocr",
        "original_consumption_receipt_hash": "h",
        "original_activation_receipt_id": "oar",
        "original_activation_receipt_hash": "h",
        "original_selector_use_status_hash": "h",
        "original_selector_use_receipt_id": "osu",
        "original_selector_use_receipt_hash": "h",
        "original_runtime_selection_receipt_id": "ors",
        "original_runtime_selection_receipt_hash": "h",
        "original_readiness_audit_id": "ora",
        "original_readiness_audit_hash": "h",
        "repeat_use_receipt_status_hash": "h",
        "repeat_use_receipt_id": "rur",
        "repeat_use_receipt_hash": "h",
        "repeat_consumption_receipt_id": "rcr",
        "repeat_consumption_receipt_hash": "h",
        "repeat_activation_receipt_id": "rar",
        "repeat_activation_receipt_hash": "h",
        "repeat_selector_use_status_hash": "h",
        "repeat_selector_use_receipt_id": "rsu",
        "repeat_selector_use_receipt_hash": "h",
        "repeat_runtime_selection_receipt_id": "rrs",
        "repeat_runtime_selection_receipt_hash": "h",
        "repeat_readiness_audit_id": "rra",
        "repeat_readiness_audit_hash": "h",
        "operator_confirmation": True,
    },
    _p("/source/ingestion/candidate-b/broader-eligible-corpus/default-scope/promotion-readiness"): {
        "client_request_id": "x",
        "readiness_mode": "candidate_b_broader_eligible_corpus_default_scope_promotion_readiness_audit_v1",
        "operator_decision": "evaluate_candidate_b_broader_scope_default_promotion_readiness",
        "trial_receipt_id": "tr",
        "trial_receipt_hash": "h",
        "trial_authority_hash": "h",
        "authority_pair_hash": "h",
        "selected_scope_classes": [],
        "operator_visible_status_confirmed": True,
        "rollback_to_baseline_confirmation": False,
        "operator_confirmation": True,
    },
    _p("/source/ingestion/candidate-b/broader-eligible-corpus/default-scope/default-promotion"): {
        "client_request_id": "x",
        "promotion_mode": "candidate_b_broader_eligible_corpus_default_scope_default_promotion_runtime_v1",
        "operator_decision": "record_candidate_b_broader_scope_default_promotion",
        "promotion_readiness_audit_id": "pra",
        "promotion_readiness_audit_hash": "h",
        "promotion_readiness_audit": {},
        "trial_receipt_id": "tr",
        "trial_receipt_hash": "h",
        "selected_scope_classes": [],
        "production_policy_hash": "h",
        "operator_visible_status_confirmed": True,
        "promotion_readiness_rendered_status_confirmed": True,
        "promotion_readiness_closeout_confirmed": True,
        "rollback_to_baseline_confirmation": False,
        "operator_confirmation": True,
    },
    _p("/source/ingestion/candidate-b/default-promotion/final-proof"): {
        "client_request_id": "x",
        "proof_mode": "candidate_b_default_promotion_final_proof_v1",
        "operator_decision": "record_candidate_b_default_promotion_final_proof",
        "readiness_audit": {},
        "operator_confirmation": True,
    },
    _p("/source/ingestion/candidate-b/default-promotion/final-proof/status"): {
        "client_request_id": "x",
        "status_mode": "candidate_b_default_promotion_final_proof_status_v1",
        "operator_decision": "inspect_candidate_b_default_promotion_final_proof_status",
        "candidate_b_runtime_bridge_receipt_id": "rbr",
        "proof_receipt_id": "pr",
    },
    _p("/source/ingestion/server-configured-directory/scan"): {
        "client_request_id": "x",
        "operator_decision": "scan_server_configured_operator_directory",
    },
    _p("/source/ingestion/server-configured-directory/material-preview"): {
        "client_request_id": "x",
        "source_ingestion_batch_id": "b",
        "source_ingestion_file_id": "f",
        "file_identity_hash": _H64,
        "authority_basis_hash": _H64,
    },
    _p("/source/ingestion/server-configured-directory/hybrid-authority/prepare"): {
        "client_request_id": "x",
        "session_id": "s",
    },
    _p("/source/ingestion/server-configured-directory/vector-retrieval"): {
        "client_request_id": "x",
        "material_snapshot_id": "m",
        "source_ingestion_batch_id": "b",
        "source_ingestion_file_id": "f",
        "content_sha256": _H64,
        "file_identity_hash": _H64,
        "authority_basis_hash": _H64,
        "payload_hash": _H64,
        "index_authority_hash": _H64,
        "embedding_index_authority_hash": _H64,
        "query_text": "q",
    },
    _p("/source/ingestion/server-configured-directory/hybrid-context-packet"): {
        "client_request_id": "x",
        "material_snapshot_id": "m",
        "source_ingestion_batch_id": "b",
        "source_ingestion_file_id": "f",
        "content_sha256": _H64,
        "file_identity_hash": _H64,
        "authority_basis_hash": _H64,
        "payload_hash": _H64,
        "index_authority_hash": _H64,
        "embedding_index_authority_hash": _H64,
        "query_text": "q",
    },
    _p("/source/ingestion/server-configured-directory/hybrid-context-packet/qualitative-analysis"): {
        "client_request_id": "x",
        "material_snapshot_id": "m",
        "source_ingestion_batch_id": "b",
        "source_ingestion_file_id": "f",
        "content_sha256": _H64,
        "file_identity_hash": _H64,
        "authority_basis_hash": _H64,
        "payload_hash": _H64,
        "index_authority_hash": _H64,
        "embedding_index_authority_hash": _H64,
        "query_text": "q",
        "analysis_question": "aq",
        "analysis_focus": "af",
    },
    _p("/source/ingestion/server-configured-directory/hybrid-context-packet/qualitative-analysis/status"): {
        "material_snapshot_id": "m",
        "source_ingestion_batch_id": "b",
        "source_ingestion_file_id": "f",
        "content_sha256": _H64,
        "file_identity_hash": _H64,
        "authority_basis_hash": _H64,
        "payload_hash": _H64,
        "index_authority_hash": _H64,
        "embedding_index_authority_hash": _H64,
        "query_text": "q",
        "analysis_question": "aq",
        "analysis_focus": "af",
    },
    _p("/source/ingestion/server-configured-directory/hybrid-context-packet/qualitative-analysis/package/commit"): {
        "client_request_id": "x",
        "material_snapshot_id": "m",
        "source_ingestion_batch_id": "b",
        "source_ingestion_file_id": "f",
        "content_sha256": _H64,
        "file_identity_hash": _H64,
        "authority_basis_hash": _H64,
        "payload_hash": _H64,
        "index_authority_hash": _H64,
        "embedding_index_authority_hash": _H64,
        "query_text": "q",
        "analysis_question": "aq",
        "analysis_focus": "af",
        "qualitative_analysis_hash": _H64,
        "source_directory_hybrid_package_review_preview_hash": _H64,
        "operator_decision": "commit_source_directory_hybrid_context_packet_qualitative_analysis_package",
    },
    _p("/source/ingestion/server-configured-directory/hybrid-context-packet/qualitative-analysis/package/review/submit"): {
        "client_request_id": "x",
        "material_snapshot_id": "m",
        "source_ingestion_batch_id": "b",
        "source_ingestion_file_id": "f",
        "content_sha256": _H64,
        "file_identity_hash": _H64,
        "authority_basis_hash": _H64,
        "payload_hash": _H64,
        "index_authority_hash": _H64,
        "embedding_index_authority_hash": _H64,
        "query_text": "q",
        "analysis_question": "aq",
        "analysis_focus": "af",
        "qualitative_analysis_hash": _H64,
        "source_directory_hybrid_package_review_preview_hash": _H64,
        "construction_basis_hash": _H64,
        "reconciliation_record_id": "r",
        "output_package_ids": ["p1"],
        "package_kinds": ["canonical_internal"],
        "payload_hashes": [_H64],
        "operator_decision": "approved",
    },
    _p("/source/ingestion/server-configured-directory/hybrid-context-packet/qualitative-analysis/handoff/export/prepare"): {
        "client_request_id": "x",
        "material_snapshot_id": "m",
        "source_ingestion_batch_id": "b",
        "source_ingestion_file_id": "f",
        "content_sha256": _H64,
        "file_identity_hash": _H64,
        "authority_basis_hash": _H64,
        "payload_hash": _H64,
        "index_authority_hash": _H64,
        "embedding_index_authority_hash": _H64,
        "query_text": "q",
        "analysis_question": "aq",
        "analysis_focus": "af",
        "qualitative_analysis_hash": _H64,
        "source_directory_hybrid_package_review_preview_hash": _H64,
        "construction_basis_hash": _H64,
        "reconciliation_record_id": "r",
        "output_package_ids": ["p1"],
        "package_kinds": ["canonical_internal"],
        "payload_hashes": [_H64],
        "package_review_submit_record_ref": "pr",
        "package_review_state": "package_review_approved",
        "handoff_target": "internal_export_envelope",
        "export_mode": "prepare_only",
        "operator_decision": "authorize_prepare",
    },
    _p("/source/ingestion/server-configured-directory/hybrid-context-packet/qualitative-analysis/handoff/export/download/prepare"): {
        "client_request_id": "x",
        "material_snapshot_id": "m",
        "source_ingestion_batch_id": "b",
        "source_ingestion_file_id": "f",
        "content_sha256": _H64,
        "file_identity_hash": _H64,
        "authority_basis_hash": _H64,
        "payload_hash": _H64,
        "index_authority_hash": _H64,
        "embedding_index_authority_hash": _H64,
        "query_text": "q",
        "analysis_question": "aq",
        "analysis_focus": "af",
        "qualitative_analysis_hash": _H64,
        "source_directory_hybrid_package_review_preview_hash": _H64,
        "construction_basis_hash": _H64,
        "reconciliation_record_id": "r",
        "output_package_ids": ["p1"],
        "package_kinds": ["canonical_internal"],
        "payload_hashes": [_H64],
        "package_review_submit_record_ref": "pr",
        "package_review_state": "package_review_approved",
        "handoff_target": "internal_export_envelope",
        "export_mode": "prepare_only",
        "prepare_record_ref": "prr",
        "handoff_export_state": "handoff_export_prepared",
        "handoff_export_envelope_ref": "hee",
        "external_export_download_target": "source_directory_hybrid_context_packet_qualitative_analysis_package_download_reference",
        "download_mode": "reference_only_prepare",
        "operator_decision": "prepare_source_directory_hybrid_external_export_download",
    },
    _p("/source/ingestion/server-configured-directory/hybrid-context-packet/qualitative-analysis/handoff/export/internal-webhook/dispatch"): {
        "client_request_id": "x",
        "material_snapshot_id": "m",
        "source_ingestion_batch_id": "b",
        "source_ingestion_file_id": "f",
        "content_sha256": _H64,
        "file_identity_hash": _H64,
        "authority_basis_hash": _H64,
        "payload_hash": _H64,
        "index_authority_hash": _H64,
        "embedding_index_authority_hash": _H64,
        "query_text": "q",
        "analysis_question": "aq",
        "analysis_focus": "af",
        "qualitative_analysis_hash": _H64,
        "source_directory_hybrid_package_review_preview_hash": _H64,
        "construction_basis_hash": _H64,
        "reconciliation_record_id": "r",
        "output_package_ids": ["p1"],
        "package_kinds": ["canonical_internal"],
        "payload_hashes": [_H64],
        "package_review_submit_record_ref": "pr",
        "package_review_state": "package_review_approved",
        "handoff_target": "internal_export_envelope",
        "export_mode": "prepare_only",
        "prepare_record_ref": "prr",
        "handoff_export_state": "handoff_export_prepared",
        "handoff_export_envelope_ref": "hee",
        "external_export_download_target": "source_directory_hybrid_context_packet_qualitative_analysis_package_download_reference",
        "download_mode": "reference_only_prepare",
        "external_export_download_record_ref": "eedr",
        "export_download_descriptor_ref": "eddr",
        "external_export_download_state": "external_export_download_prepared",
        "target_identity": "server_configured_internal_webhook_destination",
        "target_class": "real_connector_invocation",
        "dispatch_mode": "server_configured_allowlisted_internal_webhook_post",
        "operator_decision": "dispatch_source_directory_hybrid_internal_webhook",
    },
    _p("/source/ingestion/server-configured-directory/hybrid-context-packet/qualitative-analysis/handoff/export/download/deliver/status"): {
        "client_request_id": "x",
        "material_snapshot_id": "m",
        "source_ingestion_batch_id": "b",
        "source_ingestion_file_id": "f",
        "content_sha256": _H64,
        "file_identity_hash": _H64,
        "authority_basis_hash": _H64,
        "payload_hash": _H64,
        "index_authority_hash": _H64,
        "embedding_index_authority_hash": _H64,
        "query_text": "q",
        "analysis_question": "aq",
        "analysis_focus": "af",
        "qualitative_analysis_hash": _H64,
        "source_directory_hybrid_package_review_preview_hash": _H64,
        "construction_basis_hash": _H64,
        "reconciliation_record_id": "r",
        "output_package_ids": ["p1"],
        "package_kinds": ["canonical_internal"],
        "payload_hashes": [_H64],
        "package_review_submit_record_ref": "pr",
        "package_review_state": "package_review_approved",
        "handoff_target": "internal_export_envelope",
        "export_mode": "prepare_only",
        "prepare_record_ref": "prr",
        "handoff_export_state": "handoff_export_prepared",
        "handoff_export_envelope_ref": "hee",
        "external_export_download_target": "source_directory_hybrid_context_packet_qualitative_analysis_package_download_reference",
        "download_mode": "reference_only_prepare",
        "external_export_download_record_ref": "eedr",
        "export_download_descriptor_ref": "eddr",
        "external_export_download_state": "external_export_download_prepared",
        "delivery_mode": "same_origin_artifact_stream",
        "output_package_id": "op",
        "package_kind": "canonical_internal",
        "package_payload_hash": _H64,
        "operator_decision": "deliver_source_directory_hybrid_external_export_download",
    },
    _p("/source/ingestion/server-configured-directory/hybrid-context-packet/qualitative-analysis/handoff/export/download/provider-private-signed-url/prepare"): {
        "client_request_id": "x",
        "material_snapshot_id": "m",
        "source_ingestion_batch_id": "b",
        "source_ingestion_file_id": "f",
        "content_sha256": _H64,
        "file_identity_hash": _H64,
        "authority_basis_hash": _H64,
        "payload_hash": _H64,
        "index_authority_hash": _H64,
        "embedding_index_authority_hash": _H64,
        "query_text": "q",
        "analysis_question": "aq",
        "analysis_focus": "af",
        "qualitative_analysis_hash": _H64,
        "source_directory_hybrid_package_review_preview_hash": _H64,
        "construction_basis_hash": _H64,
        "reconciliation_record_id": "r",
        "output_package_ids": ["p1"],
        "package_kinds": ["canonical_internal"],
        "payload_hashes": [_H64],
        "package_review_submit_record_ref": "pr",
        "package_review_state": "package_review_approved",
        "handoff_target": "internal_export_envelope",
        "export_mode": "prepare_only",
        "prepare_record_ref": "prr",
        "handoff_export_state": "handoff_export_prepared",
        "handoff_export_envelope_ref": "hee",
        "external_export_download_target": "source_directory_hybrid_context_packet_qualitative_analysis_package_download_reference",
        "download_mode": "reference_only_prepare",
        "external_export_download_record_ref": "eedr",
        "export_download_descriptor_ref": "eddr",
        "external_export_download_state": "external_export_download_prepared",
        "delivery_mode": "provider_private_signed_url",
        "output_package_id": "op",
        "package_kind": "canonical_internal",
        "package_payload_hash": _H64,
        "recipient_scope": "rs",
        "operator_decision": "prepare_source_directory_hybrid_provider_private_signed_url",
    },
    _p("/source/ingestion/server-configured-directory/hybrid-context-packet/qualitative-analysis/handoff/export/download/provider-private-signed-url/status"): {
        "client_request_id": "x",
        "material_snapshot_id": "m",
        "source_ingestion_batch_id": "b",
        "source_ingestion_file_id": "f",
        "content_sha256": _H64,
        "file_identity_hash": _H64,
        "authority_basis_hash": _H64,
        "payload_hash": _H64,
        "index_authority_hash": _H64,
        "embedding_index_authority_hash": _H64,
        "query_text": "q",
        "analysis_question": "aq",
        "analysis_focus": "af",
        "qualitative_analysis_hash": _H64,
        "source_directory_hybrid_package_review_preview_hash": _H64,
        "construction_basis_hash": _H64,
        "reconciliation_record_id": "r",
        "output_package_ids": ["p1"],
        "package_kinds": ["canonical_internal"],
        "payload_hashes": [_H64],
        "package_review_submit_record_ref": "pr",
        "package_review_state": "package_review_approved",
        "handoff_target": "internal_export_envelope",
        "export_mode": "prepare_only",
        "prepare_record_ref": "prr",
        "handoff_export_state": "handoff_export_prepared",
        "handoff_export_envelope_ref": "hee",
        "external_export_download_target": "source_directory_hybrid_context_packet_qualitative_analysis_package_download_reference",
        "download_mode": "reference_only_prepare",
        "external_export_download_record_ref": "eedr",
        "export_download_descriptor_ref": "eddr",
        "external_export_download_state": "external_export_download_prepared",
        "delivery_mode": "provider_private_signed_url",
        "output_package_id": "op",
        "package_kind": "canonical_internal",
        "package_payload_hash": _H64,
        "provider_signed_url_receipt_id": "psu",
        "operator_decision": "inspect_source_directory_hybrid_provider_private_signed_url_status",
    },
    _p("/source/ingestion/server-configured-directory/hybrid-context-packet/qualitative-analysis/handoff/export/download/provider-private-signed-url/use"): {
        "client_request_id": "x",
        "material_snapshot_id": "m",
        "source_ingestion_batch_id": "b",
        "source_ingestion_file_id": "f",
        "content_sha256": _H64,
        "file_identity_hash": _H64,
        "authority_basis_hash": _H64,
        "payload_hash": _H64,
        "index_authority_hash": _H64,
        "embedding_index_authority_hash": _H64,
        "query_text": "q",
        "analysis_question": "aq",
        "analysis_focus": "af",
        "qualitative_analysis_hash": _H64,
        "source_directory_hybrid_package_review_preview_hash": _H64,
        "construction_basis_hash": _H64,
        "reconciliation_record_id": "r",
        "output_package_ids": ["p1"],
        "package_kinds": ["canonical_internal"],
        "payload_hashes": [_H64],
        "package_review_submit_record_ref": "pr",
        "package_review_state": "package_review_approved",
        "handoff_target": "internal_export_envelope",
        "export_mode": "prepare_only",
        "prepare_record_ref": "prr",
        "handoff_export_state": "handoff_export_prepared",
        "handoff_export_envelope_ref": "hee",
        "external_export_download_target": "source_directory_hybrid_context_packet_qualitative_analysis_package_download_reference",
        "download_mode": "reference_only_prepare",
        "external_export_download_record_ref": "eedr",
        "export_download_descriptor_ref": "eddr",
        "external_export_download_state": "external_export_download_prepared",
        "delivery_mode": "provider_private_signed_url",
        "output_package_id": "op",
        "package_kind": "canonical_internal",
        "package_payload_hash": _H64,
        "provider_signed_url_receipt_id": "psu",
        "operator_decision": "use_source_directory_hybrid_provider_private_signed_url",
    },
    _p("/source/ingestion/server-configured-directory/hybrid-context-packet/qualitative-analysis/handoff/export/download/provider-private-signed-url/revoke"): {
        "client_request_id": "x",
        "material_snapshot_id": "m",
        "source_ingestion_batch_id": "b",
        "source_ingestion_file_id": "f",
        "content_sha256": _H64,
        "file_identity_hash": _H64,
        "authority_basis_hash": _H64,
        "payload_hash": _H64,
        "index_authority_hash": _H64,
        "embedding_index_authority_hash": _H64,
        "query_text": "q",
        "analysis_question": "aq",
        "analysis_focus": "af",
        "qualitative_analysis_hash": _H64,
        "source_directory_hybrid_package_review_preview_hash": _H64,
        "construction_basis_hash": _H64,
        "reconciliation_record_id": "r",
        "output_package_ids": ["p1"],
        "package_kinds": ["canonical_internal"],
        "payload_hashes": [_H64],
        "package_review_submit_record_ref": "pr",
        "package_review_state": "package_review_approved",
        "handoff_target": "internal_export_envelope",
        "export_mode": "prepare_only",
        "prepare_record_ref": "prr",
        "handoff_export_state": "handoff_export_prepared",
        "handoff_export_envelope_ref": "hee",
        "external_export_download_target": "source_directory_hybrid_context_packet_qualitative_analysis_package_download_reference",
        "download_mode": "reference_only_prepare",
        "external_export_download_record_ref": "eedr",
        "export_download_descriptor_ref": "eddr",
        "external_export_download_state": "external_export_download_prepared",
        "delivery_mode": "provider_private_signed_url",
        "output_package_id": "op",
        "package_kind": "canonical_internal",
        "package_payload_hash": _H64,
        "provider_signed_url_receipt_id": "psu",
        "operator_decision": "revoke_source_directory_hybrid_provider_private_signed_url",
        "idempotency_key": "ik",
        "revoked_by": "rb",
        "revocation_reason": "rr",
    },
    _p("/source/ingestion/server-configured-directory/hybrid-context-packet/qualitative-analysis/handoff/export/download/deliver"): None,
    _p("/source/ingestion/server-configured-directory/qualitative-hybrid-analysis"): {
        "client_request_id": "x",
        "analysis_question": "aq",
        "analysis_focus": "af",
        "material_snapshot_id": "m",
        "source_ingestion_batch_id": "b",
        "source_ingestion_file_id": "f",
        "content_sha256": _H64,
        "file_identity_hash": _H64,
        "authority_basis_hash": _H64,
        "payload_hash": _H64,
        "index_authority_hash": _H64,
        "query_text": "q",
    },
    _p("/source/ingestion/server-configured-directory/qualitative-hybrid-analysis/status"): {
        "client_request_id": "x",
        "analysis_question": "aq",
        "analysis_focus": "af",
        "material_snapshot_id": "m",
        "source_ingestion_batch_id": "b",
        "source_ingestion_file_id": "f",
        "content_sha256": _H64,
        "file_identity_hash": _H64,
        "authority_basis_hash": _H64,
        "payload_hash": _H64,
        "index_authority_hash": _H64,
        "query_text": "q",
    },
    _p("/source/ingestion/server-configured-directory/qualitative-hybrid-analysis/package/commit"): {
        "client_request_id": "x",
        "analysis_question": "aq",
        "analysis_focus": "af",
        "material_snapshot_id": "m",
        "source_ingestion_batch_id": "b",
        "source_ingestion_file_id": "f",
        "content_sha256": _H64,
        "file_identity_hash": _H64,
        "authority_basis_hash": _H64,
        "payload_hash": _H64,
        "index_authority_hash": _H64,
        "query_text": "q",
        "qualitative_analysis_hash": _H64,
        "source_directory_package_review_preview_hash": _H64,
        "operator_decision": "commit_source_directory_qualitative_analysis_package",
    },
    _p("/source/ingestion/server-configured-directory/qualitative-hybrid-analysis/package/review/submit"): {
        "client_request_id": "x",
        "analysis_question": "aq",
        "analysis_focus": "af",
        "material_snapshot_id": "m",
        "source_ingestion_batch_id": "b",
        "source_ingestion_file_id": "f",
        "content_sha256": _H64,
        "file_identity_hash": _H64,
        "authority_basis_hash": _H64,
        "payload_hash": _H64,
        "index_authority_hash": _H64,
        "query_text": "q",
        "qualitative_analysis_hash": _H64,
        "source_directory_package_review_preview_hash": _H64,
        "construction_basis_hash": _H64,
        "reconciliation_record_id": "r",
        "output_package_ids": ["p1", "p2", "p3"],
        "package_kinds": ["canonical_internal", "user_facing", "review_facing"],
        "payload_hashes": [_H64, _H64, _H64],
        "operator_decision": "approved",
    },
    _p("/source/ingestion/server-configured-directory/qualitative-hybrid-analysis/package/supersession/preview"): {
        "client_request_id": "x",
        "analysis_question": "aq",
        "analysis_focus": "af",
        "material_snapshot_id": "m",
        "source_ingestion_batch_id": "b",
        "source_ingestion_file_id": "f",
        "content_sha256": _H64,
        "file_identity_hash": _H64,
        "authority_basis_hash": _H64,
        "payload_hash": _H64,
        "index_authority_hash": _H64,
        "query_text": "q",
        "qualitative_analysis_hash": _H64,
        "source_directory_package_review_preview_hash": _H64,
        "construction_basis_hash": _H64,
        "reconciliation_record_id": "r",
        "output_package_ids": ["p1", "p2", "p3"],
        "package_kinds": ["canonical_internal", "user_facing", "review_facing"],
        "payload_hashes": [_H64, _H64, _H64],
        "package_review_submit_record_ref": "pr",
        "package_review_state": "package_review_approved",
        "operator_decision": "preview_source_directory_package_supersession",
    },
    _p("/source/ingestion/server-configured-directory/qualitative-hybrid-analysis/package/replacement-set/record-from-supersession-preview"): {},
    _p("/source/ingestion/server-configured-directory/qualitative-hybrid-analysis/package/supersession/commit"): {},
    _p("/source/ingestion/server-configured-directory/qualitative-hybrid-analysis/package/supersession/provider-private-signed-url/prepare"): {},
    _p("/source/ingestion/server-configured-directory/qualitative-hybrid-analysis/package/supersession/provider-private-signed-url/status"): {},
    _p("/source/ingestion/server-configured-directory/qualitative-hybrid-analysis/package/supersession/provider-private-signed-url/use"): {},
    _p("/source/ingestion/server-configured-directory/qualitative-hybrid-analysis/package/supersession/provider-private-signed-url/revoke"): {},
    _p("/source/ingestion/server-configured-directory/qualitative-hybrid-analysis/handoff/export/prepare"): {
        "client_request_id": "x",
        "analysis_question": "aq",
        "analysis_focus": "af",
        "material_snapshot_id": "m",
        "source_ingestion_batch_id": "b",
        "source_ingestion_file_id": "f",
        "content_sha256": _H64,
        "file_identity_hash": _H64,
        "authority_basis_hash": _H64,
        "payload_hash": _H64,
        "index_authority_hash": _H64,
        "query_text": "q",
        "qualitative_analysis_hash": _H64,
        "source_directory_package_review_preview_hash": _H64,
        "construction_basis_hash": _H64,
        "reconciliation_record_id": "r",
        "output_package_ids": ["p1", "p2", "p3"],
        "package_kinds": ["canonical_internal", "user_facing", "review_facing"],
        "payload_hashes": [_H64, _H64, _H64],
        "package_review_submit_record_ref": "pr",
        "package_review_state": "package_review_approved",
        "handoff_target": "internal_export_envelope",
        "export_mode": "prepare_only",
        "operator_decision": "authorize_prepare",
    },
    _p("/source/ingestion/server-configured-directory/qualitative-hybrid-analysis/handoff/export/download/prepare"): {
        "client_request_id": "x",
        "analysis_question": "aq",
        "analysis_focus": "af",
        "material_snapshot_id": "m",
        "source_ingestion_batch_id": "b",
        "source_ingestion_file_id": "f",
        "content_sha256": _H64,
        "file_identity_hash": _H64,
        "authority_basis_hash": _H64,
        "payload_hash": _H64,
        "index_authority_hash": _H64,
        "query_text": "q",
        "qualitative_analysis_hash": _H64,
        "source_directory_package_review_preview_hash": _H64,
        "construction_basis_hash": _H64,
        "reconciliation_record_id": "r",
        "output_package_ids": ["p1", "p2", "p3"],
        "package_kinds": ["canonical_internal", "user_facing", "review_facing"],
        "payload_hashes": [_H64, _H64, _H64],
        "package_review_submit_record_ref": "pr",
        "package_review_state": "package_review_approved",
        "handoff_target": "internal_export_envelope",
        "export_mode": "prepare_only",
        "prepare_record_ref": "prr",
        "handoff_export_state": "handoff_export_prepared",
        "handoff_export_envelope_ref": "hee",
        "external_export_download_target": "source_directory_qualitative_analysis_package_download_reference",
        "download_mode": "reference_only_prepare",
        "operator_decision": "prepare_source_directory_external_export_download",
    },
    _p("/source/ingestion/server-configured-directory/qualitative-hybrid-analysis/handoff/export/download/deliver/status"): {
        "client_request_id": "x",
        "analysis_question": "aq",
        "analysis_focus": "af",
        "material_snapshot_id": "m",
        "source_ingestion_batch_id": "b",
        "source_ingestion_file_id": "f",
        "content_sha256": _H64,
        "file_identity_hash": _H64,
        "authority_basis_hash": _H64,
        "payload_hash": _H64,
        "index_authority_hash": _H64,
        "query_text": "q",
        "qualitative_analysis_hash": _H64,
        "source_directory_package_review_preview_hash": _H64,
        "construction_basis_hash": _H64,
        "reconciliation_record_id": "r",
        "output_package_ids": ["p1", "p2", "p3"],
        "package_kinds": ["canonical_internal", "user_facing", "review_facing"],
        "payload_hashes": [_H64, _H64, _H64],
        "package_review_submit_record_ref": "pr",
        "package_review_state": "package_review_approved",
        "handoff_target": "internal_export_envelope",
        "export_mode": "prepare_only",
        "prepare_record_ref": "prr",
        "handoff_export_state": "handoff_export_prepared",
        "handoff_export_envelope_ref": "hee",
        "external_export_download_target": "source_directory_qualitative_analysis_package_download_reference",
        "download_mode": "reference_only_prepare",
        "external_export_download_record_ref": "eedr",
        "export_download_descriptor_ref": "eddr",
        "external_export_download_state": "external_export_download_prepared",
        "delivery_mode": "same_origin_artifact_stream",
        "output_package_id": "op",
        "package_kind": "canonical_internal",
        "package_payload_hash": _H64,
        "operator_decision": "deliver_source_directory_external_export_download",
    },
    _p("/source/ingestion/server-configured-directory/qualitative-hybrid-analysis/handoff/export/download/deliver"): None,
    _p("/source/mixed-corpus/seed"): {
        "client_request_id": "x",
        "seed_mode": "raw_mixed_corpus_bridge_seed_only",
        "corpus_batch_id": "cb",
        "aps_run_id": "ar",
        "target_ids": ["t1"],
        "artifact_manifest_ref": "amr",
        "artifact_manifest_hash": _H64,
        "requested_source_classes": ["dataset_version", "aps_content_document"],
        "operator_confirmation": True,
    },
    _p("/source/mixed-corpus/materialize"): {
        "client_request_id": "x",
        "materialization_mode": "raw_mixed_existing_source_materialization_entry",
        "corpus_batch_id": "cb",
        "artifact_manifest_ref": "amr",
        "artifact_manifest_hash": _H64,
        "requested_source_classes": ["dataset_version", "aps_content_document"],
        "operator_confirmation": True,
    },
}


def _make_request(client: TestClient, path: str, payload: dict | None, extra_headers: dict | None = None):
    headers = extra_headers or {}
    if path == _p("/source/intake/upload"):
        return client.post(
            path,
            files={"file": ("test.txt", b"test-content", "text/plain")},
            data={
                "client_request_id": "x",
                "operator_decision": "upload",
                "source_label": "test",
            },
            headers=headers,
        )
    if path in _FILE_RESPONSE_ROUTES or payload is None:
        return client.post(path, json={}, headers=headers)
    return client.post(path, json=payload, headers=headers)


def _build_client(tmp_path, monkeypatch, *, auth_owner: str, trusted_proxy: bool):
    storage_dir = tmp_path / "storage"
    monkeypatch.setattr(settings, "storage_dir", str(storage_dir))
    monkeypatch.setattr(settings, "layer3_external_local_export_dir", str(tmp_path / "ext"))
    monkeypatch.setattr(settings, "layer3_internal_webhook_url", "http://127.0.0.1/wh")
    monkeypatch.setattr(settings, "layer3_internal_webhook_display_name", "test-wh")
    monkeypatch.setattr(settings, "layer3_sec_edgar_live_network_enabled", False)
    monkeypatch.setattr(settings, "auth_owner", auth_owner)
    monkeypatch.setattr(settings, "trusted_proxy_mode", trusted_proxy)
    monkeypatch.setattr(settings, "proxy_identity_header", "X-Forwarded-User")
    monkeypatch.setattr(settings, "proxy_groups_header", "X-Forwarded-Groups")
    bootstrap_storage_tree(storage_dir)
    engine = create_engine(
        "sqlite:///:memory:",
        future=True,
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
    )
    Base.metadata.create_all(engine)
    SessionLocal = sessionmaker(bind=engine, autocommit=False, autoflush=False, future=True)

    def override():
        db = SessionLocal()
        try:
            yield db
        finally:
            db.close()

    app.dependency_overrides[get_db] = override
    client = TestClient(app)
    return client


@pytest.fixture()
def client_none(tmp_path, monkeypatch):
    c = _build_client(tmp_path, monkeypatch, auth_owner="none", trusted_proxy=False)
    yield c
    app.dependency_overrides.pop(get_db, None)


@pytest.fixture()
def client_proxy_untrusted(tmp_path, monkeypatch):
    c = _build_client(tmp_path, monkeypatch, auth_owner="proxy", trusted_proxy=False)
    yield c
    app.dependency_overrides.pop(get_db, None)


@pytest.fixture()
def client_proxy_trusted(tmp_path, monkeypatch):
    c = _build_client(tmp_path, monkeypatch, auth_owner="proxy", trusted_proxy=True)
    yield c
    app.dependency_overrides.pop(get_db, None)


@pytest.mark.parametrize("path", ALL_POST_ROUTES)
def test_409_sweep_untrusted_proxy(path, client_proxy_untrusted):
    payload = _ROUTE_PAYLOADS.get(path, {})
    resp = _make_request(
        client_proxy_untrusted,
        path,
        payload,
        extra_headers={
            "X-Forwarded-User": _IDENTITY_CANARY,
            "X-Forwarded-Groups": _GROUPS_CANARY,
        },
    )
    assert resp.status_code == 409, f"{path} returned {resp.status_code}: {resp.text[:300]}"
    ct = resp.headers.get("content-type", "")
    assert ct.startswith("application/json"), f"expected application/json, got {ct}"
    body = resp.json()
    assert "untrusted_proxy_identity" in body.get("error_code", ""), body
    body_text = resp.text
    assert _IDENTITY_CANARY not in body_text, f"identity canary leaked in 409 body for {path}"
    assert _GROUPS_CANARY not in body_text, f"groups canary leaked in 409 body for {path}"


@pytest.mark.parametrize("path", ALL_POST_ROUTES)
def test_401_sweep_missing_identity(path, client_proxy_trusted):
    payload = _ROUTE_PAYLOADS.get(path, {})
    resp = _make_request(
        client_proxy_trusted,
        path,
        payload,
        extra_headers={"X-Forwarded-Groups": _GROUPS_CANARY},
    )
    assert resp.status_code == 401, f"{path} returned {resp.status_code}: {resp.text[:300]}"
    ct = resp.headers.get("content-type", "")
    assert ct.startswith("application/json"), f"expected application/json, got {ct}"
    body = resp.json()
    assert "missing_identity_authority" in body.get("error_code", ""), body
    assert _GROUPS_CANARY not in resp.text, f"groups canary leaked in 401 body for {path}"


def test_401_groups_header_absent_missing_workspace_authority(client_proxy_trusted):
    path = _p("/source/ingestion/server-configured-directory/scan")
    payload = _ROUTE_PAYLOADS[path]
    resp = client_proxy_trusted.post(
        path,
        json=payload,
        headers={"X-Forwarded-User": "operator@example.invalid"},
    )
    assert resp.status_code == 401, resp.text
    body = resp.json()
    assert "missing_workspace_authority" in body.get("error_code", ""), body


@pytest.mark.parametrize("path", ALL_POST_ROUTES)
def test_none_mode_inertness_sweep(path, client_none):
    payload = _ROUTE_PAYLOADS.get(path, {})
    resp = _make_request(client_none, path, payload)
    error_code = ""
    if resp.headers.get("content-type", "").startswith("application/json"):
        try:
            body = resp.json()
            error_code = body.get("error_code", "")
        except Exception:
            pass
    assert error_code not in _SEAM_CODES, (
        f"{path}: seam error fired under none mode: {error_code}"
    )
    assert resp.status_code != 401, (
        f"{path}: got 401 under none mode (seam must not fire)"
    )


def test_422_precedence_pin_upload_route(client_proxy_untrusted):
    resp = client_proxy_untrusted.post(
        _p("/source/intake/upload"),
        data={"operator_decision": "upload"},
        headers={
            "X-Forwarded-User": _IDENTITY_CANARY,
            "X-Forwarded-Groups": _GROUPS_CANARY,
        },
    )
    assert resp.status_code == 422, resp.text
    assert _IDENTITY_CANARY not in resp.text
    assert _GROUPS_CANARY not in resp.text


def test_422_precedence_pin_scan_route(client_proxy_untrusted):
    resp = client_proxy_untrusted.post(
        _p("/source/ingestion/server-configured-directory/scan"),
        json={"extra_forbidden_field": "value"},
        headers={
            "X-Forwarded-User": _IDENTITY_CANARY,
            "X-Forwarded-Groups": _GROUPS_CANARY,
        },
    )
    assert resp.status_code == 422, resp.text
    assert _IDENTITY_CANARY not in resp.text
    assert _GROUPS_CANARY not in resp.text


def test_file_response_deliver_hybrid_seam_error_is_json(client_proxy_untrusted):
    path = _p("/source/ingestion/server-configured-directory/hybrid-context-packet/qualitative-analysis/handoff/export/download/deliver")
    resp = client_proxy_untrusted.post(
        path,
        json={},
        headers={
            "X-Forwarded-User": _IDENTITY_CANARY,
            "X-Forwarded-Groups": _GROUPS_CANARY,
        },
    )
    assert resp.status_code == 409, resp.text
    ct = resp.headers.get("content-type", "")
    assert ct.startswith("application/json"), f"expected application/json, got {ct}"


def test_file_response_deliver_qual_seam_error_is_json(client_proxy_untrusted):
    path = _p("/source/ingestion/server-configured-directory/qualitative-hybrid-analysis/handoff/export/download/deliver")
    resp = client_proxy_untrusted.post(
        path,
        json={},
        headers={
            "X-Forwarded-User": _IDENTITY_CANARY,
            "X-Forwarded-Groups": _GROUPS_CANARY,
        },
    )
    assert resp.status_code == 409, resp.text
    ct = resp.headers.get("content-type", "")
    assert ct.startswith("application/json"), f"expected application/json, got {ct}"
