"""Layer 3 deterministic analysis methods registry.

Pure, server-internal methods that compute over working-set MEMBER METADATA
(ref_kind/ref_id counts and resolved state fields).  No IO, no randomness, no timestamps.
Same input always yields the same result.

executor_type="deterministic" products are generated by
layer3_analysis_product_generation.py which calls run_method() here.
"""

from __future__ import annotations

from collections import Counter
from dataclasses import dataclass
from typing import Any, Callable

from app.models.models import (
    L3WorkingSet,
    L3_PASS_RUN_STATUS_COMPLETED_WITH_WARNINGS,
    L3_PASS_RUN_STATUS_FAILED,
    L3_PASS_RUN_STATUS_PLANNED,
    L3_PASS_RUN_STATUS_RUNNING,
    L3_PASS_RUN_STATUS_SELECTED_NOT_STARTED,
)

# ---------------------------------------------------------------------------
# Schema ID
# ---------------------------------------------------------------------------

DETERMINISTIC_METHODS_SCHEMA_ID = "layer3.deterministic_method.v1"

# ---------------------------------------------------------------------------
# Bounding constants (binding per R4)
# ---------------------------------------------------------------------------

# Maximum refs listed in a rendered body section ("+K more" suffix).
_BODY_LIST_CAP = 20
# Maximum ref-id strings stored in result_summary per-category list.
_RESULT_LIST_CAP = 100

# Maximum distinct rollup keys stored in result_summary rollup mappings.
_ROLLUP_RESULT_CAP = 25
# Maximum rollup lines rendered in the profile body per section.
_ROLLUP_BODY_CAP = 10


# ---------------------------------------------------------------------------
# Accepted member kinds, per method.
#
# These are EXPLICIT literals, deliberately NOT derived from
# L3_WORKING_SET_MEMBER_REF_KIND_VALUES: each set lists exactly the kinds that
# the corresponding method's computation actually handles. If a new ref_kind is
# added to the model enum, these stay put, so run_method fails closed on the new
# kind for each method until that method's handler is reviewed and its set is
# updated deliberately — otherwise a state-consuming method would silently count
# the new kind in by_ref_kind while omitting it from its rollups.
# test_method_accepted_kinds_match_model_enum guards against silent drift.
# ---------------------------------------------------------------------------

_COMPOSITION_SUMMARY_KINDS: frozenset[str] = frozenset(
    {"material_snapshot", "pass_run", "output_package", "analysis_set", "prior_product"}
)
_MEMBER_STATE_PROFILE_KINDS: frozenset[str] = frozenset(
    {"material_snapshot", "pass_run", "output_package", "analysis_set", "prior_product"}
)
_STALENESS_DIAGNOSTIC_KINDS: frozenset[str] = frozenset(
    {"material_snapshot", "pass_run", "output_package", "analysis_set", "prior_product"}
)


# ---------------------------------------------------------------------------
# Internal method spec
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class _MethodSpec:
    method_id: str
    version: int
    fn: Callable[..., dict[str, Any]]
    product_kind: str
    label: str
    description: str
    consumes_member_state: bool
    render_title: Callable[..., str]
    render_body: Callable[..., str]
    # Per-method declaration of which working-set member ref_kinds are accepted.
    # run_method validates this before invoking spec.fn (fail-closed).
    accepted_member_kinds: frozenset[str]


# ---------------------------------------------------------------------------
# Pure computation functions
# ---------------------------------------------------------------------------


def _working_set_composition_summary(
    *,
    member_refs: list[dict[str, str]],
    member_count: int,
    name: str,
) -> dict[str, Any]:
    """Compute composition statistics over the working set member metadata.

    Accesses only ref_kind values — no raw payload, no external IO.
    """
    by_ref_kind: dict[str, int] = dict(
        Counter(m["ref_kind"] for m in member_refs)
    )
    distinct_ref_kinds: list[str] = sorted(by_ref_kind.keys())
    return {
        "by_ref_kind": by_ref_kind,
        "member_count": member_count,
        "distinct_ref_kinds": distinct_ref_kinds,
    }


def _render_title_composition_summary(method_id: str, *, working_set: L3WorkingSet) -> str:
    return f"Working set composition: {working_set.name}"


def _render_body_composition_summary(method_id: str, *, result: dict[str, Any]) -> str:
    by_ref_kind: dict[str, int] = result.get("by_ref_kind", {})
    member_count: int = result.get("member_count", 0)
    distinct: list[str] = result.get("distinct_ref_kinds", [])
    lines: list[str] = [
        f"Member count: {member_count}",
        f"Distinct ref kinds: {len(distinct)}",
    ]
    for kind in distinct:
        lines.append(f"  {kind}: {by_ref_kind[kind]}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# working_set_member_state_profile  (v1, product_kind="summary")
# ---------------------------------------------------------------------------


def _cap_rollup(counter: Counter, cap: int) -> dict[str, int]:
    """Return an ordered dict of at most *cap* entries from *counter*.

    Selection: top entries by (-count, key) — count descending, key ascending
    (a total order, deterministic under ties).  Counts inside the mapping stay
    exact; only the number of listed keys is capped.
    """
    ordered = sorted(counter.items(), key=lambda kv: (-kv[1], kv[0]))
    return dict(ordered[:cap])


def _working_set_member_state_profile(
    *,
    member_refs: list[dict[str, str]],
    member_count: int,
    name: str,
    member_states: list[dict[str, Any]],
) -> dict[str, Any]:
    """Per-ref-kind rollup of resolved state fields plus an unresolved section.

    Pure function over (member_refs, member_count, name, member_states).
    No IO, no timestamps.
    """
    # Build lookup: (ref_kind, ref_id) -> state dict
    state_by_key: dict[tuple[str, str], dict[str, Any]] = {
        (s["ref_kind"], s["ref_id"]): s for s in member_states
    }

    # Per-kind rollup accumulators
    prior_product_by_lifecycle: Counter[str] = Counter()
    pass_run_by_status: Counter[str] = Counter()
    output_package_by_status: Counter[str] = Counter()
    material_snapshot_by_source_plane: Counter[str] = Counter()
    analysis_set_info: list[dict[str, Any]] = []  # for group/unit count derivation

    by_ref_kind: dict[str, int] = dict(Counter(m["ref_kind"] for m in member_refs))

    unresolved_refs: list[str] = []

    for m in member_refs:
        rk = m["ref_kind"]
        rid = m["ref_id"]
        state = state_by_key.get((rk, rid))
        if state is None or not state.get("resolved", False):
            unresolved_refs.append(rid)
            continue
        if rk == "prior_product":
            prior_product_by_lifecycle[(state.get("lifecycle_status") or "unknown")] += 1
        elif rk == "pass_run":
            pass_run_by_status[(state.get("status") or "unknown")] += 1
        elif rk == "output_package":
            output_package_by_status[(state.get("status") or "unknown")] += 1
        elif rk == "material_snapshot":
            material_snapshot_by_source_plane[(state.get("source_plane") or "unknown")] += 1
        elif rk == "analysis_set":
            analysis_set_info.append(state)

    # analysis_set lens: group/unit counts are resolver-produced integers (R4)
    total_group_refs = sum(s.get("group_count") or 0 for s in analysis_set_info)
    total_unit_refs = sum(s.get("unit_count") or 0 for s in analysis_set_info)
    analysis_set_rollup = {
        "count": len(analysis_set_info),
        "total_group_refs": total_group_refs,
        "total_unit_refs": total_unit_refs,
    }

    # Sort for determinism before applying cap (order-invariant regardless of member_refs order)
    unresolved_refs.sort()
    # Cap unresolved list at _RESULT_LIST_CAP for result_summary
    unresolved_count = len(unresolved_refs)
    unresolved_capped = unresolved_refs[:_RESULT_LIST_CAP]

    return {
        "member_count": member_count,
        "by_ref_kind": by_ref_kind,
        "prior_product": {
            "by_lifecycle_status": _cap_rollup(prior_product_by_lifecycle, _ROLLUP_RESULT_CAP),
            "distinct_lifecycle_status_values": len(prior_product_by_lifecycle),
        },
        "pass_run": {
            "by_status": _cap_rollup(pass_run_by_status, _ROLLUP_RESULT_CAP),
            "distinct_status_values": len(pass_run_by_status),
        },
        "output_package": {
            "by_status": _cap_rollup(output_package_by_status, _ROLLUP_RESULT_CAP),
            "distinct_status_values": len(output_package_by_status),
        },
        "material_snapshot": {
            "by_source_plane": _cap_rollup(material_snapshot_by_source_plane, _ROLLUP_RESULT_CAP),
            "distinct_source_plane_values": len(material_snapshot_by_source_plane),
        },
        "analysis_set": analysis_set_rollup,
        # PROMINENT unresolved section (R5)
        "unresolved": {
            "count": unresolved_count,
            "refs": unresolved_capped,
        },
    }


def _render_title_member_state_profile(method_id: str, *, working_set: L3WorkingSet) -> str:
    return f"Member state profile: {working_set.name}"


def _render_body_member_state_profile(method_id: str, *, result: dict[str, Any]) -> str:
    lines: list[str] = [
        f"Member count: {result.get('member_count', 0)}",
    ]
    # by_ref_kind rollup
    by_ref_kind = result.get("by_ref_kind", {})
    if by_ref_kind:
        lines.append("Composition by ref kind:")
        for kind in sorted(by_ref_kind):
            lines.append(f"  {kind}: {by_ref_kind[kind]}")

    # per-kind rollup lines (counts only — R4)
    def _render_rollup_section(label: str, mapping: dict[str, int], distinct_count: int) -> None:
        if not mapping:
            return
        lines.append(f"{label}:")
        # mapping is already ordered by (-count, key) from _cap_rollup; honour that order
        shown = list(mapping.items())[:_ROLLUP_BODY_CAP]
        for k, v in shown:
            lines.append(f"  {k}: {v}")
        remainder = distinct_count - len(shown)
        if remainder > 0:
            lines.append(f"  +{remainder} more values")

    pp_section = result.get("prior_product", {})
    _render_rollup_section(
        "Prior product lifecycle statuses",
        pp_section.get("by_lifecycle_status", {}),
        pp_section.get("distinct_lifecycle_status_values", len(pp_section.get("by_lifecycle_status", {}))),
    )

    pr_section = result.get("pass_run", {})
    _render_rollup_section(
        "Pass run statuses",
        pr_section.get("by_status", {}),
        pr_section.get("distinct_status_values", len(pr_section.get("by_status", {}))),
    )

    op_section = result.get("output_package", {})
    _render_rollup_section(
        "Output package statuses",
        op_section.get("by_status", {}),
        op_section.get("distinct_status_values", len(op_section.get("by_status", {}))),
    )

    ms_section = result.get("material_snapshot", {})
    _render_rollup_section(
        "Material snapshot source planes",
        ms_section.get("by_source_plane", {}),
        ms_section.get("distinct_source_plane_values", len(ms_section.get("by_source_plane", {}))),
    )

    asr = result.get("analysis_set", {})
    if asr.get("count", 0):
        lines.append(
            f"Analysis sets: {asr['count']} "
            f"(group refs: {asr.get('total_group_refs', 0)}, "
            f"unit refs: {asr.get('total_unit_refs', 0)})"
        )

    # PROMINENT unresolved section (R5)
    unresolved = result.get("unresolved", {})
    unresolved_count = unresolved.get("count", 0)
    if unresolved_count > 0:
        refs = unresolved.get("refs", [])
        shown = refs[:_BODY_LIST_CAP]
        remainder = unresolved_count - len(shown)
        lines.append(f"UNRESOLVED members: {unresolved_count}")
        for rid in shown:
            lines.append(f"  - {rid}")
        if remainder > 0:
            lines.append(f"  +{remainder} more")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# working_set_staleness_diagnostic  (v1, product_kind="diagnostic")
# ---------------------------------------------------------------------------

# Pass-run statuses that indicate "incomplete" (informational, do not affect clean)
_INCOMPLETE_STATUSES: frozenset[str] = frozenset({
    L3_PASS_RUN_STATUS_PLANNED,
    L3_PASS_RUN_STATUS_SELECTED_NOT_STARTED,
    L3_PASS_RUN_STATUS_RUNNING,
})


def _working_set_staleness_diagnostic(
    *,
    member_refs: list[dict[str, str]],
    member_count: int,
    name: str,
    member_states: list[dict[str, Any]],
) -> dict[str, Any]:
    """Flag superseded prior_products, failed pass_runs, and unresolved members.

    clean := all three flagged category counts == 0 (R12).
    Informational (do not affect clean): incomplete_pass_runs,
    pass_runs_completed_with_warnings.

    Pure function — no IO, no timestamps.
    """
    state_by_key: dict[tuple[str, str], dict[str, Any]] = {
        (s["ref_kind"], s["ref_id"]): s for s in member_states
    }

    superseded_refs: list[str] = []
    failed_pass_run_refs: list[str] = []
    unresolved_refs: list[str] = []
    incomplete_pass_run_count = 0
    completed_with_warnings_count = 0

    for m in member_refs:
        rk = m["ref_kind"]
        rid = m["ref_id"]
        state = state_by_key.get((rk, rid))
        if state is None or not state.get("resolved", False):
            unresolved_refs.append(rid)
            continue
        if rk == "prior_product":
            if state.get("lifecycle_status") == "superseded":
                superseded_refs.append(rid)
        elif rk == "pass_run":
            status = state.get("status", "")
            if status == L3_PASS_RUN_STATUS_FAILED:
                failed_pass_run_refs.append(rid)
            elif status in _INCOMPLETE_STATUSES:
                incomplete_pass_run_count += 1
            elif status == L3_PASS_RUN_STATUS_COMPLETED_WITH_WARNINGS:
                completed_with_warnings_count += 1

    # Sort for determinism before applying caps (order-invariant regardless of member_refs order)
    superseded_refs.sort()
    failed_pass_run_refs.sort()
    unresolved_refs.sort()

    # Cap at _RESULT_LIST_CAP for result_summary lists
    clean = (
        len(superseded_refs) == 0
        and len(failed_pass_run_refs) == 0
        and len(unresolved_refs) == 0
    )

    return {
        "clean": clean,
        "member_count": member_count,
        # Flagged categories (affect clean)
        "superseded_prior_products": {
            "count": len(superseded_refs),
            "members": superseded_refs[:_RESULT_LIST_CAP],
        },
        "failed_pass_runs": {
            "count": len(failed_pass_run_refs),
            "members": failed_pass_run_refs[:_RESULT_LIST_CAP],
        },
        "unresolved_members": {
            "count": len(unresolved_refs),
            "members": unresolved_refs[:_RESULT_LIST_CAP],
        },
        # Informational counts (do not affect clean)
        "incomplete_pass_runs": incomplete_pass_run_count,
        "pass_runs_completed_with_warnings": completed_with_warnings_count,
    }


def _render_title_staleness_diagnostic(method_id: str, *, working_set: L3WorkingSet) -> str:
    return f"Staleness diagnostic: {working_set.name}"


def _render_body_staleness_diagnostic(method_id: str, *, result: dict[str, Any]) -> str:
    clean = result.get("clean", False)
    # Count total flagged issues
    issue_count = (
        result.get("superseded_prior_products", {}).get("count", 0)
        + result.get("failed_pass_runs", {}).get("count", 0)
        + result.get("unresolved_members", {}).get("count", 0)
    )
    if clean:
        verdict = "Staleness verdict: clean"
    else:
        verdict = f"Staleness verdict: stale — {issue_count} issue(s)"

    lines: list[str] = [verdict]

    def _section(label: str, category_key: str) -> None:
        cat = result.get(category_key, {})
        count = cat.get("count", 0)
        if count == 0:
            return
        members = cat.get("members", [])
        shown = members[:_BODY_LIST_CAP]
        remainder = count - len(shown)
        lines.append(f"{label}: {count}")
        for rid in shown:
            lines.append(f"  - {rid}")
        if remainder > 0:
            lines.append(f"  +{remainder} more")

    _section("Superseded prior products", "superseded_prior_products")
    _section("Failed pass runs", "failed_pass_runs")
    _section("Unresolved members", "unresolved_members")

    # Informational counts
    incomplete = result.get("incomplete_pass_runs", 0)
    with_warnings = result.get("pass_runs_completed_with_warnings", 0)
    if incomplete or with_warnings:
        lines.append(f"Incomplete pass runs (informational): {incomplete}")
        lines.append(f"Pass runs completed with warnings (informational): {with_warnings}")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Registry
# ---------------------------------------------------------------------------

DETERMINISTIC_METHODS: dict[str, _MethodSpec] = {
    "working_set_composition_summary": _MethodSpec(
        method_id="working_set_composition_summary",
        version=2,
        fn=_working_set_composition_summary,
        product_kind="metric",
        label="Composition summary",
        description="Counts member ref_kind strings; no state access.",
        consumes_member_state=False,
        render_title=_render_title_composition_summary,
        render_body=_render_body_composition_summary,
        accepted_member_kinds=_COMPOSITION_SUMMARY_KINDS,
    ),
    "working_set_member_state_profile": _MethodSpec(
        method_id="working_set_member_state_profile",
        version=1,
        fn=_working_set_member_state_profile,
        product_kind="summary",
        label="Member state profile",
        description=(
            "Per-ref-kind rollups of resolved state fields "
            "(lifecycle_status, status, source_plane, etc.) "
            "plus an unresolved-member section."
        ),
        consumes_member_state=True,
        render_title=_render_title_member_state_profile,
        render_body=_render_body_member_state_profile,
        accepted_member_kinds=_MEMBER_STATE_PROFILE_KINDS,
    ),
    "working_set_staleness_diagnostic": _MethodSpec(
        method_id="working_set_staleness_diagnostic",
        version=1,
        fn=_working_set_staleness_diagnostic,
        product_kind="diagnostic",
        label="Staleness diagnostic",
        description=(
            "Flags superseded prior products, failed pass runs, "
            "and unresolved members; emits a clean/stale verdict."
        ),
        consumes_member_state=True,
        render_title=_render_title_staleness_diagnostic,
        render_body=_render_body_staleness_diagnostic,
        accepted_member_kinds=_STALENESS_DIAGNOSTIC_KINDS,
    ),
}


# ---------------------------------------------------------------------------
# Public runner
# ---------------------------------------------------------------------------


def run_method(
    method_id: str,
    *,
    working_set: L3WorkingSet,
    member_states: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    """Run the named deterministic method over the working set.

    Returns a result dict containing method_id, method_version, and the
    computed summary payload.  Raises KeyError if method_id is unknown
    (caller maps this to a Layer3AnalysisProductError).

    For methods with consumes_member_state=True, member_states MUST be
    provided; passing None raises ValueError (fail-closed per R1).

    Deterministic: identical (working_set, member_states) -> identical result.
    """
    spec = DETERMINISTIC_METHODS[method_id]  # KeyError propagates to caller

    # Fail-closed: validate every distinct ref_kind in the working set against
    # the method's declared accepted_member_kinds.  A single unsupported kind
    # among otherwise supported ones still raises (no partial accept).
    # Only kind names are included in the message — never ref_ids or bodies.
    present_kinds: set[str] = {m["ref_kind"] for m in working_set.member_refs_json}
    unsupported = present_kinds - spec.accepted_member_kinds
    if unsupported:
        raise ValueError(
            f"method '{method_id}' does not accept member kinds: {sorted(unsupported)};"
            f" accepted: {sorted(spec.accepted_member_kinds)}"
        )

    if spec.consumes_member_state:
        if member_states is None:
            raise ValueError(
                f"method '{method_id}' requires member_states but None was provided."
            )
        summary = spec.fn(
            member_refs=list(working_set.member_refs_json),
            member_count=working_set.member_count,
            name=working_set.name,
            member_states=member_states,
        )
    else:
        summary = spec.fn(
            member_refs=list(working_set.member_refs_json),
            member_count=working_set.member_count,
            name=working_set.name,
        )

    return {
        "method_id": spec.method_id,
        "method_version": spec.version,
        **summary,
    }


# ---------------------------------------------------------------------------
# Title / body renderers (pure, stable) — thin dispatchers over spec callables
# ---------------------------------------------------------------------------


def render_title(method_id: str, *, working_set: L3WorkingSet) -> str:
    """Return a deterministic, human-readable product title."""
    spec = DETERMINISTIC_METHODS.get(method_id)
    if spec is not None:
        return spec.render_title(method_id, working_set=working_set)
    # Generic fallback for unknown method ids (preserves existing contract)
    return f"Deterministic analysis: {working_set.name} [{method_id}]"


# ---------------------------------------------------------------------------
# Quality signals
# ---------------------------------------------------------------------------

# Maximum number of limitation strings (defensive cap; categories are few)
_QUALITY_LIMITATIONS_CAP = 10


def method_quality_signals(method_id: str, *, result: dict[str, Any]) -> dict[str, Any]:
    """Derive a bounded {confidence_level, limitations} from a method result.

    confidence_level in {"high","medium","low"}. limitations is a bounded list of
    short strings (kind+count only — never ref_ids/paths/bodies). Pure + deterministic.
    """
    if method_id == "working_set_composition_summary":
        # Pure count over member metadata; can never be degraded.
        return {"confidence_level": "high", "limitations": []}

    if method_id == "working_set_member_state_profile":
        u = result.get("unresolved", {}).get("count", 0)
        if u == 0:
            return {"confidence_level": "high", "limitations": []}
        limitations: list[str] = [f"{u} unresolved member(s)"]
        return {"confidence_level": "medium", "limitations": limitations[:_QUALITY_LIMITATIONS_CAP]}

    if method_id == "working_set_staleness_diagnostic":
        superseded_n = result.get("superseded_prior_products", {}).get("count", 0)
        failed_n = result.get("failed_pass_runs", {}).get("count", 0)
        unresolved_n = result.get("unresolved_members", {}).get("count", 0)
        incomplete_n = result.get("incomplete_pass_runs", 0)
        with_warnings_n = result.get("pass_runs_completed_with_warnings", 0)

        if result.get("clean", False):
            # Informational-only limitations (do not degrade confidence).
            info: list[str] = []
            if incomplete_n > 0:
                info.append(f"{incomplete_n} incomplete pass run(s)")
            if with_warnings_n > 0:
                info.append(f"{with_warnings_n} pass run(s) completed with warnings")
            return {
                "confidence_level": "high",
                "limitations": sorted(info)[:_QUALITY_LIMITATIONS_CAP],
            }
        else:
            # Not clean: confidence is low. One limitation per non-zero flagged category.
            # Append order is fixed (failed -> superseded -> unresolved, then the
            # informational signals) so the list is deterministic.
            lims: list[str] = []
            if failed_n > 0:
                lims.append(f"{failed_n} failed pass run(s)")
            if superseded_n > 0:
                lims.append(f"{superseded_n} superseded prior product(s)")
            if unresolved_n > 0:
                lims.append(f"{unresolved_n} unresolved member(s)")
            # Informational signals are appended after flagged ones.
            if incomplete_n > 0:
                lims.append(f"{incomplete_n} incomplete pass run(s)")
            if with_warnings_n > 0:
                lims.append(f"{with_warnings_n} pass run(s) completed with warnings")
            return {
                "confidence_level": "low",
                "limitations": lims[:_QUALITY_LIMITATIONS_CAP],
            }

    # Unknown method: no signals available.
    return {"confidence_level": "high", "limitations": []}


def _quality_footer(method_id: str, *, result: dict[str, Any]) -> str:
    """Build the confidence/limitations footer lines for render_body."""
    signals = method_quality_signals(method_id, result=result)
    level = signals["confidence_level"]
    limitations: list[str] = signals["limitations"]
    lines = [f"Confidence: {level}"]
    if limitations:
        lines.append("Limitations:")
        for lim in limitations:
            lines.append(f"  - {lim}")
    return "\n".join(lines)


def render_body(method_id: str, *, result: dict[str, Any]) -> str:
    """Return a deterministic, human-readable product body."""
    spec = DETERMINISTIC_METHODS.get(method_id)
    if spec is not None:
        core = spec.render_body(method_id, result=result)
        footer = _quality_footer(method_id, result=result)
        return core + "\n" + footer
    # Generic fallback for unknown method ids (preserves existing contract).
    # No quality footer here: generate_analysis_product rejects unknown method
    # ids before body generation, so this degenerate path never reaches a stored
    # product or provenance — it exists only for legacy/internal callers.
    return f"method_id={result.get('method_id')} method_version={result.get('method_version')}"
