"""Shared Layer 3 workbench bootstrap contract builder."""

from __future__ import annotations

from typing import Any, Mapping, Sequence

from app.services.layer3_readiness_contract import EXECUTION_READINESS_SCHEMA_ID
from app.services.layer3_response_contract import base_response

BOOTSTRAP_SCHEMA_ID = "layer3.workbench_bootstrap.v1"

BOOTSTRAP_FEATURE_FLAGS: Mapping[str, bool] = {
    "plan_preview": True,
    "plan_approval": True,
    "execution_selection": True,
    "analysis_execution_start": True,
    "execution_result_status": True,
    "execution_result_review": True,
    "package_review_preview": True,
    "package_construction_commit": True,
    "package_review_submit": True,
    "handoff_export_prepare": True,
    "aps_handoff_dispatch": True,
    "external_export_download_prepare": True,
    "external_export_download_deliver": True,
    "internal_connector_dispatch_record": True,
    "package_supersession_preview": True,
    "replacement_package_set_authority": True,
    "package_supersession_commit": True,
    "replacement_package_artifact_manifest": True,
    "replacement_package_namespace": True,
    "plan_revision_recovery": True,
    "analysis_execution": False,
    "single_aps_doc_qualitative_execution": True,
    "broad_qualitative_execution": False,
    "hybrid_execution": False,
    "rag_vector_retrieval": False,
    "package_review": False,
    "handoff": False,
    "external_export": False,
    "dispatch": False,
    "runtime_snapshot_db_writes": False,
    "schema_widening": False,
    "typing_override_enabled": False,
}


def build_bootstrap_contract(
    *,
    route: str,
    api_root: str,
    supported_source_classes: Sequence[str],
    unsupported_source_classes: Sequence[str],
    gate_labels: Sequence[str],
    active_gate_labels: Sequence[str],
    unavailable_gate_labels: Sequence[str],
    state_action_contract: Mapping[str, Any],
    authority_rail: Mapping[str, Any],
) -> dict[str, Any]:
    return {
        **base_response(BOOTSTRAP_SCHEMA_ID),
        "route": route,
        "api_root": api_root,
        "supported_source_classes": list(supported_source_classes),
        "preview_only_source_classes": [],
        "unsupported_source_classes": list(unsupported_source_classes),
        "gate_labels": list(gate_labels),
        "active_gate_labels": list(active_gate_labels),
        "unavailable_gate_labels": list(unavailable_gate_labels),
        "state_action_contract": dict(state_action_contract),
        "features": dict(BOOTSTRAP_FEATURE_FLAGS),
        "execution_readiness": {
            "schema_id": EXECUTION_READINESS_SCHEMA_ID,
            "execution_admitted": False,
            "execution_enabled": False,
            "execution_selection_admitted": True,
            "execution_selection_endpoint": f"{api_root}/execution/select",
            "analysis_execution_admitted": False,
            "analysis_execution_start_admitted": True,
            "analysis_execution_start_endpoint": f"{api_root}/execution/start",
            "execution_result_status_admitted": True,
            "execution_result_status_endpoint": f"{api_root}/execution/result/status",
            "execution_result_review_admitted": True,
            "execution_result_review_endpoint": f"{api_root}/execution/result/review",
            "package_review_preview_admitted": True,
            "package_review_preview_endpoint": f"{api_root}/package/review/preview",
            "package_construction_commit_admitted": True,
            "package_construction_commit_endpoint": f"{api_root}/package/review/commit",
            "package_review_submit_admitted": True,
            "package_review_submit_endpoint": f"{api_root}/package/review/submit",
            "handoff_export_prepare_admitted": True,
            "handoff_export_prepare_endpoint": f"{api_root}/handoff/export/prepare",
            "aps_handoff_dispatch_admitted": True,
            "aps_handoff_dispatch_endpoint": f"{api_root}/handoff/aps/dispatch",
            "external_export_download_prepare_admitted": True,
            "external_export_download_prepare_endpoint": f"{api_root}/handoff/export/download/prepare",
            "external_export_download_deliver_admitted": True,
            "external_export_download_deliver_endpoint": f"{api_root}/handoff/export/download/deliver",
            "internal_connector_dispatch_record_admitted": True,
            "internal_connector_dispatch_record_endpoint": f"{api_root}/handoff/connector/record",
            "package_supersession_preview_admitted": True,
            "package_supersession_preview_endpoint": f"{api_root}/package/mutation/preview",
            "replacement_package_set_authority_admitted": True,
            "replacement_package_set_authority_endpoint": f"{api_root}/package/replacement-set/record",
            "package_supersession_commit_admitted": True,
            "package_supersession_commit_endpoint": f"{api_root}/package/supersession/commit",
            "replacement_package_artifact_manifest_admitted": True,
            "replacement_package_artifact_manifest_endpoint": (
                f"{api_root}/package/replacement-artifact/manifest/record"
            ),
            "replacement_package_namespace_admitted": True,
            "replacement_package_namespace_endpoint": f"{api_root}/package/replacement-namespace/record",
            "plan_revision_recovery_admitted": True,
            "plan_revision_recovery_endpoint": f"{api_root}/plan/revision/recover",
            "package_review_admitted": False,
            "external_handoff_admitted": False,
            "external_export_admitted": False,
            "dispatch_admitted": False,
            "readiness_state": "execution_readiness_blocked",
            "readiness_endpoint": f"{api_root}/readiness",
        },
        "authority_rail": dict(authority_rail),
    }
