"""Layer 3 deterministic analysis methods registry.

Pure, server-internal methods that compute over working-set MEMBER METADATA
(ref_kind/ref_id counts) only.  No IO, no randomness, no timestamps.
Same input always yields the same result.

executor_type="deterministic" products are generated by
layer3_analysis_product_generation.py which calls run_method() here.
"""

from __future__ import annotations

from collections import Counter
from dataclasses import dataclass
from typing import Any, Callable

from app.models.models import L3WorkingSet

# ---------------------------------------------------------------------------
# Schema ID
# ---------------------------------------------------------------------------

DETERMINISTIC_METHODS_SCHEMA_ID = "layer3.deterministic_method.v1"


# ---------------------------------------------------------------------------
# Internal method spec
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class _MethodSpec:
    method_id: str
    version: int
    fn: Callable[..., dict[str, Any]]


# ---------------------------------------------------------------------------
# Pure computation functions
# ---------------------------------------------------------------------------


def _working_set_composition_summary(
    *,
    member_refs: list[dict[str, str]],
    member_count: int,
    name: str,
) -> dict[str, Any]:
    """Compute composition statistics over the working set member metadata.

    Accesses only ref_kind values — no raw payload, no external IO.
    """
    by_ref_kind: dict[str, int] = dict(
        Counter(m["ref_kind"] for m in member_refs)
    )
    distinct_ref_kinds: list[str] = sorted(by_ref_kind.keys())
    return {
        "by_ref_kind": by_ref_kind,
        "member_count": member_count,
        "distinct_ref_kinds": distinct_ref_kinds,
    }


# ---------------------------------------------------------------------------
# Registry
# ---------------------------------------------------------------------------

DETERMINISTIC_METHODS: dict[str, _MethodSpec] = {
    "working_set_composition_summary": _MethodSpec(
        method_id="working_set_composition_summary",
        version=1,
        fn=_working_set_composition_summary,
    ),
}


# ---------------------------------------------------------------------------
# Public runner
# ---------------------------------------------------------------------------


def run_method(method_id: str, *, working_set: L3WorkingSet) -> dict[str, Any]:
    """Run the named deterministic method over the working set.

    Returns a result dict containing method_id, method_version, and the
    computed summary payload.  Raises KeyError if method_id is unknown
    (caller maps this to a Layer3AnalysisProductError).

    Deterministic: identical working set -> identical result.
    """
    spec = DETERMINISTIC_METHODS[method_id]  # KeyError propagates to caller
    summary = spec.fn(
        member_refs=list(working_set.member_refs_json),
        member_count=working_set.member_count,
        name=working_set.name,
    )
    return {
        "method_id": spec.method_id,
        "method_version": spec.version,
        **summary,
    }


# ---------------------------------------------------------------------------
# Title / body renderers (pure, stable)
# ---------------------------------------------------------------------------


def render_title(method_id: str, *, working_set: L3WorkingSet) -> str:
    """Return a deterministic, human-readable product title."""
    if method_id == "working_set_composition_summary":
        return f"Working set composition: {working_set.name}"
    return f"Deterministic analysis: {working_set.name} [{method_id}]"


def render_body(method_id: str, *, result: dict[str, Any]) -> str:
    """Return a deterministic, human-readable product body."""
    if method_id == "working_set_composition_summary":
        by_ref_kind: dict[str, int] = result.get("by_ref_kind", {})
        member_count: int = result.get("member_count", 0)
        distinct: list[str] = result.get("distinct_ref_kinds", [])
        lines: list[str] = [
            f"Member count: {member_count}",
            f"Distinct ref kinds: {len(distinct)}",
        ]
        for kind in distinct:
            lines.append(f"  {kind}: {by_ref_kind[kind]}")
        return "\n".join(lines)
    return f"method_id={result.get('method_id')} method_version={result.get('method_version')}"
