from __future__ import annotations

from typing import Any

from app.services.layer3_preview_contract import (
    material_preview_hash_contract,
    plan_preview_hash_contract,
)
from app.services.layer3_response_contract import base_response


EXECUTION_READINESS_SCHEMA_ID = "layer3.execution_readiness_contract.v1"

READINESS_REQUIRED_GATES = (
    "proof-manifest",
    "state-model",
    "preview-hash",
    "idempotency",
    "concurrency",
    "revision-recovery",
    "approved-plan-cancel",
    "approved-plan-correction",
    "output-taxonomy",
    "source-breadth",
    "execution-selection",
    "analysis-execution-start",
    "result-status",
    "result-review",
    "package-review-preview",
    "package-construction",
    "package-review-submit",
    "handoff-export-prepare",
    "aps-handoff-dispatch",
    "external-export-download-prepare",
    "external-export-download-deliver",
    "browser-proof",
)
READINESS_IMPLEMENTED_GATES = (
    "proof-manifest",
    "state-model",
    "preview-hash",
    "idempotency",
    "concurrency",
    "revision-recovery",
    "approved-plan-cancel",
    "execution-selection",
    "analysis-execution-start",
    "result-status",
    "result-review",
    "package-review-preview",
    "package-construction",
    "package-review-submit",
    "handoff-export-prepare",
    "aps-handoff-dispatch",
    "external-export-download-prepare",
    "external-export-download-deliver",
)
READINESS_DEFERRED_GATES = (
    "approved-plan-correction",
    "output-taxonomy",
    "source-breadth",
    "browser-proof",
)


def build_readiness_contract(
    *,
    api_root: str,
    state_model: dict[str, Any],
    state_action_contract: dict[str, Any],
    authority_matrix_contract: dict[str, Any],
) -> dict[str, Any]:
    return {
        **base_response(EXECUTION_READINESS_SCHEMA_ID),
        "execution_admitted": False,
        "execution_enabled": False,
        "execution_selection_admitted": True,
        "execution_selection_endpoint": f"{api_root}/execution/select",
        "analysis_execution_admitted": False,
        "analysis_execution_start_admitted": True,
        "analysis_execution_start_endpoint": f"{api_root}/execution/start",
        "single_aps_doc_qualitative_execution_admitted": True,
        "execution_result_status_admitted": True,
        "execution_result_status_endpoint": f"{api_root}/execution/result/status",
        "execution_result_review_admitted": True,
        "execution_result_review_endpoint": f"{api_root}/execution/result/review",
        "package_review_preview_admitted": True,
        "package_review_preview_endpoint": f"{api_root}/package/review/preview",
        "package_construction_commit_admitted": True,
        "package_construction_commit_endpoint": f"{api_root}/package/review/commit",
        "package_review_submit_admitted": True,
        "package_review_submit_endpoint": f"{api_root}/package/review/submit",
        "handoff_export_prepare_admitted": True,
        "handoff_export_prepare_endpoint": f"{api_root}/handoff/export/prepare",
        "aps_handoff_dispatch_admitted": True,
        "aps_handoff_dispatch_endpoint": f"{api_root}/handoff/aps/dispatch",
        "external_export_download_prepare_admitted": True,
        "external_export_download_prepare_endpoint": f"{api_root}/handoff/export/download/prepare",
        "external_export_download_deliver_admitted": True,
        "external_export_download_deliver_endpoint": f"{api_root}/handoff/export/download/deliver",
        "internal_connector_dispatch_record_admitted": True,
        "internal_connector_dispatch_record_endpoint": f"{api_root}/handoff/connector/record",
        "package_supersession_preview_admitted": True,
        "package_supersession_preview_endpoint": f"{api_root}/package/mutation/preview",
        "replacement_package_set_authority_admitted": True,
        "replacement_package_set_authority_endpoint": f"{api_root}/package/replacement-set/record",
        "package_supersession_commit_admitted": True,
        "package_supersession_commit_endpoint": f"{api_root}/package/supersession/commit",
        "replacement_package_artifact_manifest_admitted": True,
        "replacement_package_artifact_manifest_endpoint": f"{api_root}/package/replacement-artifact/manifest/record",
        "replacement_package_namespace_admitted": True,
        "replacement_package_namespace_endpoint": f"{api_root}/package/replacement-namespace/record",
        "plan_revision_recovery_admitted": True,
        "plan_revision_recovery_endpoint": f"{api_root}/plan/revision/recover",
        "approved_plan_cancel_admitted": True,
        "approved_plan_cancel_endpoint": f"{api_root}/plan/approved/cancel",
        "package_review_admitted": False,
        "external_handoff_admitted": False,
        "external_export_admitted": False,
        "dispatch_admitted": False,
        "readiness_state": "execution_readiness_blocked",
        "required_gates": list(READINESS_REQUIRED_GATES),
        "implemented_gates": list(READINESS_IMPLEMENTED_GATES),
        "deferred_gates": list(READINESS_DEFERRED_GATES),
        "state_model": state_model,
        "state_action_contract": state_action_contract,
        "authority_matrix_contract": authority_matrix_contract,
        "preview_hash_contract": plan_preview_hash_contract(),
        "material_preview_hash_contract": material_preview_hash_contract(),
        "idempotency_contract": {
            "schema_id": "layer3.idempotency_contract.v1",
            "client_request_id_supported": True,
            "client_request_id_required_current_slice": False,
            "client_request_id_required_for_gate_b_decision": True,
            "client_request_id_required_for_execution_selection": True,
            "client_request_id_required_for_analysis_execution_start": True,
            "client_request_id_required_for_execution_result_status": False,
            "client_request_id_required_for_execution_result_review": True,
            "client_request_id_required_for_package_review_preview": False,
            "client_request_id_required_for_package_construction_commit": True,
            "client_request_id_required_for_package_review_submit": True,
            "client_request_id_required_for_handoff_export_prepare": True,
            "client_request_id_required_for_aps_handoff_dispatch": True,
            "client_request_id_required_for_external_export_download_prepare": True,
            "client_request_id_required_for_external_export_download_deliver": True,
            "client_request_id_required_for_package_supersession_preview": True,
            "client_request_id_required_for_replacement_package_set_authority": True,
            "client_request_id_required_for_package_supersession_commit": True,
            "client_request_id_required_for_replacement_package_artifact_manifest": True,
            "client_request_id_required_for_replacement_package_namespace": True,
            "client_request_id_required_for_plan_revision_recovery": True,
            "client_request_id_required_for_approved_plan_cancel": True,
            "duplicate_gate_b_decision": "same required client_request_id, provided source context, provided material_preview_id, and decision manifest uses a durable Gate B idempotency claim and returns existing Gate B session; conflicts fail closed",
            "gate_b_decision_idempotency_scope": "durable_claim_and_post_commit_retry",
            "gate_b_decision_concurrent_duplicate_lock": True,
            "duplicate_plan_approval": "returns existing approved-plan conflict; no duplicate L3AnalysisPlan",
            "duplicate_plan_revision": "returns existing revision-control conflict; no duplicate revision-control state",
            "duplicate_execution_selection": "same client_request_id and same approved plan returns existing selection; conflicts fail closed",
            "duplicate_analysis_execution_start": "same client_request_id and same selected pass returns existing execution state; conflicts fail closed",
            "duplicate_execution_result_status": "read-only status inspection does not create idempotency state",
            "duplicate_execution_result_review": "same client_request_id and same selected pass returns existing review state; conflicts fail closed",
            "duplicate_package_review_preview": "read-only package-review preview inspection does not create idempotency state",
            "duplicate_package_construction_commit": "same client_request_id and same authority basis returns existing package rows; conflicts fail closed",
            "duplicate_package_review_submit": "same authority basis and same operator decision returns existing package-review state; conflicts fail closed",
            "duplicate_handoff_export_prepare": "same authority basis and same operator decision returns existing preparation state; conflicts fail closed",
            "duplicate_aps_handoff_dispatch": "same client_request_id and same prepared-envelope authority returns existing APS handoff state; conflicts fail closed",
            "duplicate_external_export_download_prepare": "same client_request_id and same APS handoff authority returns existing readiness state; conflicts fail closed",
            "duplicate_external_export_download_deliver": "read-only delivery revalidates the recorded readiness descriptor and may re-stream the same existing artifact",
            "duplicate_package_supersession_preview": "read-only package supersession preview recomputes the same package-set and downstream-dependency hash without persistence",
            "duplicate_replacement_package_set_authority": "same client_request_id or authority basis returns existing replacement package-set authority; conflicts fail closed",
            "duplicate_package_supersession_commit": "same client_request_id or commit basis returns existing immutable supersession lineage record; conflicts fail closed",
            "duplicate_replacement_package_artifact_manifest": "same client_request_id or authority basis returns existing verified replacement artifact manifest; conflicts fail closed",
            "duplicate_replacement_package_namespace": "same client_request_id and authority basis returns existing replacement namespace row; conflicts fail closed",
            "duplicate_plan_revision_recovery": "same client_request_id and same recorded revision-control authority returns existing recovery state; conflicts fail closed",
            "duplicate_approved_plan_cancel": "same client_request_id and same approved-plan authority basis returns existing cancellation state; conflicts fail closed",
            "duplicate_without_client_request_id": "server-authoritative state conflicts still prevent duplicate durable approval or revision-control state",
            "analysis_execution": "broad analysis execution remains blocked; selected-pass execution start is admitted separately",
        },
        "concurrency_contract": {
            "schema_id": "layer3.concurrency_contract.v1",
            "approval_revision_mutual_exclusion": True,
            "server_authority": "durable_session_row_lock_or_equivalent_transaction",
            "browser_in_flight_lock_is_authoritative": False,
            "execution_selection_uses_session_and_plan_locks": True,
            "analysis_execution_start_uses_session_plan_and_pass_locks": True,
            "execution_result_review_uses_session_and_pass_locks": True,
            "package_review_preview_is_read_only": True,
            "package_construction_commit_uses_session_plan_and_pass_locks": True,
            "package_review_submit_uses_session_reconciliation_and_package_locks": True,
            "handoff_export_prepare_uses_session_reconciliation_and_package_locks": True,
            "aps_handoff_dispatch_uses_session_reconciliation_and_package_locks": True,
            "external_export_download_prepare_uses_session_reconciliation_and_package_locks": True,
            "external_export_download_deliver_uses_session_reconciliation_and_package_locks": True,
            "package_supersession_preview_is_read_only": True,
            "replacement_package_set_authority_uses_unique_request_and_basis": True,
            "package_supersession_commit_uses_unique_request_and_basis": True,
            "replacement_package_artifact_manifest_uses_unique_request_and_basis": True,
            "replacement_package_artifact_manifest_is_manifest_only": True,
            "replacement_package_namespace_uses_unique_request_basis_and_manifest_kind": True,
            "replacement_package_namespace_uses_separate_replacement_table": True,
            "plan_revision_recovery_uses_session_lock": True,
            "plan_revision_recovery_is_preview_refresh_only": True,
            "approved_plan_cancel_uses_session_and_plan_locks": True,
            "approved_plan_cancel_without_replacement_only": True,
            "broad_analysis_execution_requires_later_freeze": True,
        },
        "deferred_decisions": {
            "schema_id": "layer3.deferred_execution_decisions.v1",
            "revision_recovery": "admitted only as preview-refresh recovery from terminal pre-approval revision-control state",
            "approved_plan_cancel": "admitted only as cancellation without replacement of the current approved plan before pass-run creation",
            "approved_plan_correction": "only approved_plan_cancel_without_replacement is admitted; approved-plan supersession, replacement, reopening, and deletion still require later freezes",
            "output_taxonomy": "requires later freeze before results or package UI",
            "source_breadth": "requires later freeze before RAG/vector/upload/local-directory expansion",
            "package_construction": "admitted only for selected-pass workbench commit; broader package construction still requires later freeze",
            "package_review_submit": "admitted only for bounded decision recording over an already constructed workbench package set",
            "aps_handoff_dispatch": "admitted only for server-side APS evidence-bundle handoff after handoff_export_prepared",
            "external_export_download_prepare": "admitted only as a reference-only readiness descriptor after aps_handoff_dispatched; browser download remains disabled",
            "external_export_download_deliver": "admitted only as same-origin streaming of the already validated APS evidence-bundle artifact after recorded readiness; public or signed URLs remain disabled",
            "internal_connector_dispatch_record": "admitted only as response-safe internal dispatch intent record after associated-cohort external export/download readiness; external invocation and destination writes remain blocked",
            "package_supersession_preview": "admitted only as read-only immutable package supersession preview; package row mutation, payload rewrite, and supersession commit remain blocked",
            "replacement_package_set_authority": "admitted only as a durable metadata authority record; package row mutation, payload writes, and broad package mutation remain blocked",
            "package_supersession_commit": "admitted only as a durable immutable lineage record; package row mutation, payload writes, and broad package mutation remain blocked",
            "replacement_package_artifact_manifest": "admitted only as server-side manifest verification of existing replacement refs and hashes; artifact generation, package row mutation, payload writes, and broad package mutation remain blocked",
            "replacement_package_namespace": "admitted only as separate replacement output-package namespace rows over verified manifest artifacts; source L3OutputPackage rows, payload writes, and broad package mutation remain blocked",
            "external_handoff_export_dispatch": "browser download, public/signed URL generation, connector dispatch, destination selection, and non-APS dispatch still require later freezes",
        },
    }
