"""Layer 3 deterministic analysis methods registry.

Pure, server-internal methods that compute over working-set MEMBER METADATA
(ref_kind/ref_id counts and resolved state fields).  No IO, no randomness, no timestamps.
Same input always yields the same result.

executor_type="deterministic" products are generated by
layer3_analysis_product_generation.py which calls run_method() here.
"""

from __future__ import annotations

from collections import Counter
from dataclasses import dataclass
from typing import Any, Callable

from app.models.models import (
    L3WorkingSet,
    L3_PASS_RUN_STATUS_COMPLETED_WITH_WARNINGS,
    L3_PASS_RUN_STATUS_FAILED,
    L3_PASS_RUN_STATUS_PLANNED,
    L3_PASS_RUN_STATUS_RUNNING,
    L3_PASS_RUN_STATUS_SELECTED_NOT_STARTED,
)

# ---------------------------------------------------------------------------
# Schema ID
# ---------------------------------------------------------------------------

DETERMINISTIC_METHODS_SCHEMA_ID = "layer3.deterministic_method.v1"

# ---------------------------------------------------------------------------
# Bounding constants (binding per R4)
# ---------------------------------------------------------------------------

# Maximum refs listed in a rendered body section ("+K more" suffix).
_BODY_LIST_CAP = 20
# Maximum ref-id strings stored in result_summary per-category list.
_RESULT_LIST_CAP = 100


# ---------------------------------------------------------------------------
# Internal method spec
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class _MethodSpec:
    method_id: str
    version: int
    fn: Callable[..., dict[str, Any]]
    product_kind: str
    label: str
    description: str
    consumes_member_state: bool
    render_title: Callable[..., str]
    render_body: Callable[..., str]


# ---------------------------------------------------------------------------
# Pure computation functions
# ---------------------------------------------------------------------------


def _working_set_composition_summary(
    *,
    member_refs: list[dict[str, str]],
    member_count: int,
    name: str,
) -> dict[str, Any]:
    """Compute composition statistics over the working set member metadata.

    Accesses only ref_kind values — no raw payload, no external IO.
    """
    by_ref_kind: dict[str, int] = dict(
        Counter(m["ref_kind"] for m in member_refs)
    )
    distinct_ref_kinds: list[str] = sorted(by_ref_kind.keys())
    return {
        "by_ref_kind": by_ref_kind,
        "member_count": member_count,
        "distinct_ref_kinds": distinct_ref_kinds,
    }


def _render_title_composition_summary(method_id: str, *, working_set: L3WorkingSet) -> str:
    return f"Working set composition: {working_set.name}"


def _render_body_composition_summary(method_id: str, *, result: dict[str, Any]) -> str:
    by_ref_kind: dict[str, int] = result.get("by_ref_kind", {})
    member_count: int = result.get("member_count", 0)
    distinct: list[str] = result.get("distinct_ref_kinds", [])
    lines: list[str] = [
        f"Member count: {member_count}",
        f"Distinct ref kinds: {len(distinct)}",
    ]
    for kind in distinct:
        lines.append(f"  {kind}: {by_ref_kind[kind]}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# working_set_member_state_profile  (v1, product_kind="summary")
# ---------------------------------------------------------------------------


def _working_set_member_state_profile(
    *,
    member_refs: list[dict[str, str]],
    member_count: int,
    name: str,
    member_states: list[dict[str, Any]],
) -> dict[str, Any]:
    """Per-ref-kind rollup of resolved state fields plus an unresolved section.

    Pure function over (member_refs, member_count, name, member_states).
    No IO, no timestamps.
    """
    # Build lookup: (ref_kind, ref_id) -> state dict
    state_by_key: dict[tuple[str, str], dict[str, Any]] = {
        (s["ref_kind"], s["ref_id"]): s for s in member_states
    }

    # Per-kind rollup accumulators
    prior_product_by_lifecycle: Counter[str] = Counter()
    pass_run_by_status: Counter[str] = Counter()
    output_package_by_status: Counter[str] = Counter()
    material_snapshot_by_source_plane: Counter[str] = Counter()
    analysis_set_info: list[dict[str, Any]] = []  # for group/unit count derivation

    by_ref_kind: dict[str, int] = dict(Counter(m["ref_kind"] for m in member_refs))

    unresolved_refs: list[str] = []

    for m in member_refs:
        rk = m["ref_kind"]
        rid = m["ref_id"]
        state = state_by_key.get((rk, rid))
        if state is None or not state.get("resolved", False):
            unresolved_refs.append(rid)
            continue
        if rk == "prior_product":
            prior_product_by_lifecycle[(state.get("lifecycle_status") or "unknown")] += 1
        elif rk == "pass_run":
            pass_run_by_status[(state.get("status") or "unknown")] += 1
        elif rk == "output_package":
            output_package_by_status[(state.get("status") or "unknown")] += 1
        elif rk == "material_snapshot":
            material_snapshot_by_source_plane[(state.get("source_plane") or "unknown")] += 1
        elif rk == "analysis_set":
            analysis_set_info.append(state)

    # analysis_set lens: group/unit counts are resolver-produced integers (R4)
    total_group_refs = sum(s.get("group_count") or 0 for s in analysis_set_info)
    total_unit_refs = sum(s.get("unit_count") or 0 for s in analysis_set_info)
    analysis_set_rollup = {
        "count": len(analysis_set_info),
        "total_group_refs": total_group_refs,
        "total_unit_refs": total_unit_refs,
    }

    # Sort for determinism before applying cap (order-invariant regardless of member_refs order)
    unresolved_refs.sort()
    # Cap unresolved list at _RESULT_LIST_CAP for result_summary
    unresolved_count = len(unresolved_refs)
    unresolved_capped = unresolved_refs[:_RESULT_LIST_CAP]

    return {
        "member_count": member_count,
        "by_ref_kind": by_ref_kind,
        "prior_product": {"by_lifecycle_status": dict(prior_product_by_lifecycle)},
        "pass_run": {"by_status": dict(pass_run_by_status)},
        "output_package": {"by_status": dict(output_package_by_status)},
        "material_snapshot": {"by_source_plane": dict(material_snapshot_by_source_plane)},
        "analysis_set": analysis_set_rollup,
        # PROMINENT unresolved section (R5)
        "unresolved": {
            "count": unresolved_count,
            "refs": unresolved_capped,
        },
    }


def _render_title_member_state_profile(method_id: str, *, working_set: L3WorkingSet) -> str:
    return f"Member state profile: {working_set.name}"


def _render_body_member_state_profile(method_id: str, *, result: dict[str, Any]) -> str:
    lines: list[str] = [
        f"Member count: {result.get('member_count', 0)}",
    ]
    # by_ref_kind rollup
    by_ref_kind = result.get("by_ref_kind", {})
    if by_ref_kind:
        lines.append("Composition by ref kind:")
        for kind in sorted(by_ref_kind):
            lines.append(f"  {kind}: {by_ref_kind[kind]}")

    # per-kind rollup lines (counts only — R4)
    pp = result.get("prior_product", {}).get("by_lifecycle_status", {})
    if pp:
        lines.append("Prior product lifecycle statuses:")
        for k in sorted(pp):
            lines.append(f"  {k}: {pp[k]}")

    pr = result.get("pass_run", {}).get("by_status", {})
    if pr:
        lines.append("Pass run statuses:")
        for k in sorted(pr):
            lines.append(f"  {k}: {pr[k]}")

    op = result.get("output_package", {}).get("by_status", {})
    if op:
        lines.append("Output package statuses:")
        for k in sorted(op):
            lines.append(f"  {k}: {op[k]}")

    ms = result.get("material_snapshot", {}).get("by_source_plane", {})
    if ms:
        lines.append("Material snapshot source planes:")
        for k in sorted(ms):
            lines.append(f"  {k}: {ms[k]}")

    asr = result.get("analysis_set", {})
    if asr.get("count", 0):
        lines.append(
            f"Analysis sets: {asr['count']} "
            f"(group refs: {asr.get('total_group_refs', 0)}, "
            f"unit refs: {asr.get('total_unit_refs', 0)})"
        )

    # PROMINENT unresolved section (R5)
    unresolved = result.get("unresolved", {})
    unresolved_count = unresolved.get("count", 0)
    if unresolved_count > 0:
        refs = unresolved.get("refs", [])
        shown = refs[:_BODY_LIST_CAP]
        remainder = unresolved_count - len(shown)
        lines.append(f"UNRESOLVED members: {unresolved_count}")
        for rid in shown:
            lines.append(f"  - {rid}")
        if remainder > 0:
            lines.append(f"  +{remainder} more")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# working_set_staleness_diagnostic  (v1, product_kind="diagnostic")
# ---------------------------------------------------------------------------

# Pass-run statuses that indicate "incomplete" (informational, do not affect clean)
_INCOMPLETE_STATUSES: frozenset[str] = frozenset({
    L3_PASS_RUN_STATUS_PLANNED,
    L3_PASS_RUN_STATUS_SELECTED_NOT_STARTED,
    L3_PASS_RUN_STATUS_RUNNING,
})


def _working_set_staleness_diagnostic(
    *,
    member_refs: list[dict[str, str]],
    member_count: int,
    name: str,
    member_states: list[dict[str, Any]],
) -> dict[str, Any]:
    """Flag superseded prior_products, failed pass_runs, and unresolved members.

    clean := all three flagged category counts == 0 (R12).
    Informational (do not affect clean): incomplete_pass_runs,
    pass_runs_completed_with_warnings.

    Pure function — no IO, no timestamps.
    """
    state_by_key: dict[tuple[str, str], dict[str, Any]] = {
        (s["ref_kind"], s["ref_id"]): s for s in member_states
    }

    superseded_refs: list[str] = []
    failed_pass_run_refs: list[str] = []
    unresolved_refs: list[str] = []
    incomplete_pass_run_count = 0
    completed_with_warnings_count = 0

    for m in member_refs:
        rk = m["ref_kind"]
        rid = m["ref_id"]
        state = state_by_key.get((rk, rid))
        if state is None or not state.get("resolved", False):
            unresolved_refs.append(rid)
            continue
        if rk == "prior_product":
            if state.get("lifecycle_status") == "superseded":
                superseded_refs.append(rid)
        elif rk == "pass_run":
            status = state.get("status", "")
            if status == L3_PASS_RUN_STATUS_FAILED:
                failed_pass_run_refs.append(rid)
            elif status in _INCOMPLETE_STATUSES:
                incomplete_pass_run_count += 1
            elif status == L3_PASS_RUN_STATUS_COMPLETED_WITH_WARNINGS:
                completed_with_warnings_count += 1

    # Sort for determinism before applying caps (order-invariant regardless of member_refs order)
    superseded_refs.sort()
    failed_pass_run_refs.sort()
    unresolved_refs.sort()

    # Cap at _RESULT_LIST_CAP for result_summary lists
    clean = (
        len(superseded_refs) == 0
        and len(failed_pass_run_refs) == 0
        and len(unresolved_refs) == 0
    )

    return {
        "clean": clean,
        "member_count": member_count,
        # Flagged categories (affect clean)
        "superseded_prior_products": {
            "count": len(superseded_refs),
            "members": superseded_refs[:_RESULT_LIST_CAP],
        },
        "failed_pass_runs": {
            "count": len(failed_pass_run_refs),
            "members": failed_pass_run_refs[:_RESULT_LIST_CAP],
        },
        "unresolved_members": {
            "count": len(unresolved_refs),
            "members": unresolved_refs[:_RESULT_LIST_CAP],
        },
        # Informational counts (do not affect clean)
        "incomplete_pass_runs": incomplete_pass_run_count,
        "pass_runs_completed_with_warnings": completed_with_warnings_count,
    }


def _render_title_staleness_diagnostic(method_id: str, *, working_set: L3WorkingSet) -> str:
    return f"Staleness diagnostic: {working_set.name}"


def _render_body_staleness_diagnostic(method_id: str, *, result: dict[str, Any]) -> str:
    clean = result.get("clean", False)
    # Count total flagged issues
    issue_count = (
        result.get("superseded_prior_products", {}).get("count", 0)
        + result.get("failed_pass_runs", {}).get("count", 0)
        + result.get("unresolved_members", {}).get("count", 0)
    )
    if clean:
        verdict = "Staleness verdict: clean"
    else:
        verdict = f"Staleness verdict: stale — {issue_count} issue(s)"

    lines: list[str] = [verdict]

    def _section(label: str, category_key: str) -> None:
        cat = result.get(category_key, {})
        count = cat.get("count", 0)
        if count == 0:
            return
        members = cat.get("members", [])
        shown = members[:_BODY_LIST_CAP]
        remainder = count - len(shown)
        lines.append(f"{label}: {count}")
        for rid in shown:
            lines.append(f"  - {rid}")
        if remainder > 0:
            lines.append(f"  +{remainder} more")

    _section("Superseded prior products", "superseded_prior_products")
    _section("Failed pass runs", "failed_pass_runs")
    _section("Unresolved members", "unresolved_members")

    # Informational counts
    incomplete = result.get("incomplete_pass_runs", 0)
    with_warnings = result.get("pass_runs_completed_with_warnings", 0)
    if incomplete or with_warnings:
        lines.append(f"Incomplete pass runs (informational): {incomplete}")
        lines.append(f"Pass runs completed with warnings (informational): {with_warnings}")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Registry
# ---------------------------------------------------------------------------

DETERMINISTIC_METHODS: dict[str, _MethodSpec] = {
    "working_set_composition_summary": _MethodSpec(
        method_id="working_set_composition_summary",
        version=1,
        fn=_working_set_composition_summary,
        product_kind="summary",
        label="Composition summary",
        description="Counts member ref_kind strings; no state access.",
        consumes_member_state=False,
        render_title=_render_title_composition_summary,
        render_body=_render_body_composition_summary,
    ),
    "working_set_member_state_profile": _MethodSpec(
        method_id="working_set_member_state_profile",
        version=1,
        fn=_working_set_member_state_profile,
        product_kind="summary",
        label="Member state profile",
        description=(
            "Per-ref-kind rollups of resolved state fields "
            "(lifecycle_status, status, source_plane, etc.) "
            "plus an unresolved-member section."
        ),
        consumes_member_state=True,
        render_title=_render_title_member_state_profile,
        render_body=_render_body_member_state_profile,
    ),
    "working_set_staleness_diagnostic": _MethodSpec(
        method_id="working_set_staleness_diagnostic",
        version=1,
        fn=_working_set_staleness_diagnostic,
        product_kind="diagnostic",
        label="Staleness diagnostic",
        description=(
            "Flags superseded prior products, failed pass runs, "
            "and unresolved members; emits a clean/stale verdict."
        ),
        consumes_member_state=True,
        render_title=_render_title_staleness_diagnostic,
        render_body=_render_body_staleness_diagnostic,
    ),
}


# ---------------------------------------------------------------------------
# Public runner
# ---------------------------------------------------------------------------


def run_method(
    method_id: str,
    *,
    working_set: L3WorkingSet,
    member_states: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    """Run the named deterministic method over the working set.

    Returns a result dict containing method_id, method_version, and the
    computed summary payload.  Raises KeyError if method_id is unknown
    (caller maps this to a Layer3AnalysisProductError).

    For methods with consumes_member_state=True, member_states MUST be
    provided; passing None raises ValueError (fail-closed per R1).

    Deterministic: identical (working_set, member_states) -> identical result.
    """
    spec = DETERMINISTIC_METHODS[method_id]  # KeyError propagates to caller

    if spec.consumes_member_state:
        if member_states is None:
            raise ValueError(
                f"method '{method_id}' requires member_states but None was provided."
            )
        summary = spec.fn(
            member_refs=list(working_set.member_refs_json),
            member_count=working_set.member_count,
            name=working_set.name,
            member_states=member_states,
        )
    else:
        summary = spec.fn(
            member_refs=list(working_set.member_refs_json),
            member_count=working_set.member_count,
            name=working_set.name,
        )

    return {
        "method_id": spec.method_id,
        "method_version": spec.version,
        **summary,
    }


# ---------------------------------------------------------------------------
# Title / body renderers (pure, stable) — thin dispatchers over spec callables
# ---------------------------------------------------------------------------


def render_title(method_id: str, *, working_set: L3WorkingSet) -> str:
    """Return a deterministic, human-readable product title."""
    spec = DETERMINISTIC_METHODS.get(method_id)
    if spec is not None:
        return spec.render_title(method_id, working_set=working_set)
    # Generic fallback for unknown method ids (preserves existing contract)
    return f"Deterministic analysis: {working_set.name} [{method_id}]"


def render_body(method_id: str, *, result: dict[str, Any]) -> str:
    """Return a deterministic, human-readable product body."""
    spec = DETERMINISTIC_METHODS.get(method_id)
    if spec is not None:
        return spec.render_body(method_id, result=result)
    # Generic fallback for unknown method ids (preserves existing contract)
    return f"method_id={result.get('method_id')} method_version={result.get('method_version')}"
